### ISSUE TITLE
Cinecalidad is not working properly

### ISSUE THREAD

**Issue by JorTurFer** [Jackett/Jackett#10595]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment
Docker with Jackett v0.17.145

**Are you using a proxy or VPN?** [yes/no]
no

### Description
The last days, cinecalidad works wrong, the problem is that some url are relative and not absolute. The problem are this two lines: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Cinecalidad.cs#L182-L183
They assume that the url from the DOM are absolute and these assumption breaks the torrent download and the poster

[List steps to reproduce the error and details on what happens and what you expected to happen]

Add cinecalidad as an indexer and try to download manually some movie like [La Llorona (2019)](https://www.cinecalidad.im/espana/pelicula/la-llorona-2019-online-descarga/)

### Logged Error Messages

```powershell
12-21 14:28:39 Info Manual search in cinecalidad for la llorona => Found 1 releases (from cache)
12-21 14:28:43 Error Error downloading. indexer: cinecalidad path: file:///espana/pelicula/la-llorona-2019-online-descarga/
System.ArgumentException: Only 'http' and 'https' schemes are allowed. (Parameter 'value')
   at System.Net.Http.HttpRequestMessage.set_RequestUri(Uri value)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 105
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 485
   at Jackett.Common.Indexers.Cinecalidad.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 131
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
```

### Screenshots

![image](https://user-images.githubusercontent.com/36899226/102782201-3d27ae00-4399-11eb-95eb-d8ec255037e1.png)

**Comment by ngosang** [comment]
Try Jackett v0.17.145
I pushed a fix for this yesterday.

**Comment by JorTurFer** [comment]
I used this version and the indexer still fails.
I tried also in master branch before create my PR and also fails. 
The indexer shows results, but when you try to download from one of them, the system fails.
P.D: Sorry for any mistake in the text, I am using my mobile

**Comment by ngosang** [comment]
Thank you for reporting. I will take a look.

**Comment by garfield69** [comment]
Jackett 0.17.159
