### ISSUE TITLE
[btdigg] test failed

### ISSUE THREAD

**Issue by TuxNuX** [Jackett/Jackett#10743]
### Environment

**OS**: Linux 64bit

**Jackett Version**: 0.17.197

**Are you using a proxy or VPN?** [no]

### Description

impossible connect with jackett (test failed), good work with web browser https://btdig.com/

### Logged Error Messages

[btdigg] Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://203.63.138.254/.: Parse error (Test)

**Comment by ilike2burnthing** [comment]
Assuming that's not your public IP, it looks like an ISP block.

When accessing the site in browser, is this on the same device and IP as Jackett?

**Comment by TuxNuX** [comment]
Yes same browser, same laptop, same ip for jackett and website

![Screenshot_20210107_173926](https://user-images.githubusercontent.com/17123357/103918665-5e192e80-510f-11eb-981d-99e19d43ef6e.png)

**Comment by TuxNuX** [comment]
ping and whois good work
![Screenshot_20210107_174400](https://user-images.githubusercontent.com/17123357/103919323-31194b80-5110-11eb-8e7e-5545b635a4e6.png)

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by TuxNuX** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5785692/log.txt)

**Comment by ilike2burnthing** [comment]
Thanks. If you open BTDigg in a private/incognito window, are you presented with a recaptcha challenge? That's what is showing for Jackett in the logs.

**Comment by TuxNuX** [comment]
no captcha in incognito 

I specify that I installed for jackett the "FlareSolverr"

**Comment by ilike2burnthing** [comment]
Yea, that's a current issue - https://github.com/Jackett/Jackett/issues/10579

Not sure what caused your initial problem, but at least that one was resolved. You can follow the issue above for any further progress.

**Comment by TuxNuX** [comment]
Yes I already reported it about a month ago

but possible the other problem still exists but the https://github.com/Jackett/Jackett/issues/10579 is perhaps "priority" and the one to repair the other problem to return
