### ISSUE TITLE
Jackett deletes itself on clean install on Linux

### ISSUE THREAD

**Issue by lovegnome** [Jackett/Jackett#11463]
This possibly matches some other config migration issues, but doesn't quite match. My repro steps are pretty simple:

1. Make sure there's no config in .config/Jackett
2. Extract the files
3. Run Jackett
4. When Jackett fails, note that the Jackett folder got deleted.

Other notes:
After the failure, .config/Jackett is filled with Jackett binaries
If I stage my backup config from before this started happening, with UpdateDisabled set to true, it still occurs
I can sort of work around it by launching Jackett from within the Jackett folder so that the folder can't be deleted. But it's not a very good workaround.

[sadfg ~/test] rm -rf ~/.config/Jackett
[sadfg ~/test] ls
Jackett.Binaries.LinuxAMDx64.tar.gz
[sadfg ~/test] tar xzf Jackett.Binaries.LinuxAMDx64.tar.gz
[sadfg ~/test] ls
Jackett  Jackett.Binaries.LinuxAMDx64.tar.gz
[sadfg ~/test] Jackett/jackett
04-03 06:33:33 Info Starting Jackett v0.17.838
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Configuration.FileExtensions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Configuration.FileExtensions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Jackett.Server.Program.Main(String[] args)
Aborted
[sadfg ~/test] ls
Jackett.Binaries.LinuxAMDx64.tar.gz
[sadfg ~/test] cat ~/.config/Jackett/log.txt
2021-04-03 06:33:33.0788 Info Starting Jackett v0.17.838
[sadfg ~/test] uname -a
Linux sadfg 4.19.123-feral #2 SMP Mon May 18 09:01:14 BST 2020 x86_64 GNU/Linux
[sadfg ~/test]

**Comment by NinjaLikesCheez** [comment]
If possible, would you be able to try against this changeset and see if the behaviour continues: https://github.com/Jackett/Jackett/pull/11465

Thanks!

**Comment by ilike2burnthing** [comment]
Same issue? https://github.com/Jackett/Jackett/issues/11457

Follow the instructions there and let us know your results.

@NinjaLikesCheez could this be related to the current issue you're working on? If so, would it be resolved by https://github.com/Jackett/Jackett/pull/11465?

**Comment by KaiSforza** [comment]
Can confirm this is happening as well. It seems like it moves everything into /config (or whatever the config is set to)

```
╰> docker run --rm -it kaictl/jackett /bin/bash
groups: cannot find name for group ID 1000
I have no name!@7b6acb77f07b:/$ ls -lah Jackett/jackett
-rwxr-xr-x 1 1000 1000 136K Apr  3 00:51 Jackett/jackett
I have no name!@7b6acb77f07b:/$ ls config/
I have no name!@7b6acb77f07b:/$ /Jackett/jackett --NoRestart
04-03 18:54:13 Info Starting Jackett v0.17.838 
Unhandled exception. System.IO.IOException: Access to the path '/Jackett' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Jackett.Common.Services.ConfigurationService.CreateOrMigrateSettings()
   at Jackett.Server.Program.Main(String[] args)
Aborted (core dumped)
I have no name!@7b6acb77f07b:/$ ls -lah config/Jackett/jackett
-rwxr-xr-x 1 1000 1000 136K Apr  3 00:51 config/Jackett/jackett
```

**Comment by KaiSforza** [comment]
I just did a quick lazy bisect and it seems like it happened between bd2905f and 7479b52, since 0.17.815 works but 826 doesn't work.

**Comment by ilike2burnthing** [comment]
Presumably https://github.com/Jackett/Jackett/commit/f5688f289db201512b3e5b7ddcd25359aea8f99e then, which should now be fixed with https://github.com/Jackett/Jackett/pull/11465. If there's something there which you think still needs addressed, let us know.

**Comment by Drugwash2** [comment]
Is there a release ready that fixes this issue? It still happens on Linux Mint 19.2 x64 (Ubuntu 18.04 based) upon auto-update.
Initially I thought it was related to switching to .NET 5.0 beginning with 0.17, so I installed the latest version before the switch: 0.16.2374. That one works fine, no folder deletion.
Then I installed the .NET 5.0 runtime, however behavior was unchanged after installing it.
After reading the conversation above I installed 0.17.815 and indeed it works fine too. Weird thing is, the **jackett** and **JackettUpdater** executables are now of Unknown type bearing a generic file icon, while previously they were recognized as executables and bearing the proper icon in the default file manager (Nemo). This may or may not be an issue with .NET 5.0 file associations, dunno - haven't rebooted or logged out/in yet after installing .NET 5.0.

**Comment by ilike2burnthing** [comment]
You can download the [drop folder](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3225/artifacts?artifactName=drop&api-version=6.0&%24format=zip). It contains all versions of the release for Windows, Mac, and Linux.

**Comment by KaiSforza** [comment]
I'll test that when I get home. Looks like it should be fixed though.

**Comment by Drugwash2** [comment]
Unfortunately it's not fixed in the drop package. :(

More info if it may help:
- the main Jackett folder is manually unpacked in the home folder => /home/<username>/Jackett
-the executable is launched through a desktop launcher pointing to /home/<username>/Jackett/jackett
- there is no /opt/jackett/Jackett folder
- the folder in ~/config/Jackett seems to contain all Jackett files plus logs, Definitions folder, Indexes folder

Everything works fine with versions up to 0.17.815.
Later versions tested which failed: 0.17.830, 0.17.838, current version in drop.zip as of 2021.04.04 01:20 EEST.

Thank you both for looking into it, hopefully it will be fixed soon.

**Comment by ilike2burnthing** [comment]
@Drugwash2 revert to v0.17.815 and disable automatic updates. The next release should be out in ~6hrs. Check https://github.com/Jackett/Jackett/releases after that time, re-enable automatic updates, and see if updating normally resolves the issue (some things are only triggered this way, rather than by installing over an old version, just not sure if this is one of them).

@KaiSforza (or anyone else) I'd still be interested to see if it's the same for you, so if you could try the drop folder as well that'd be a great help (no rush, just whenever you're able).

**Comment by Drugwash2** [comment]
Thank you, I had already downgraded to 0.17.815 and disabled automatic updates pending a resolution. The new version should probably be up by the time I wake up (in about 10-12 hours) and will check it again then. Please ask if there's any extra info I could provide in order to help with this. Thank you again.

**Comment by KaiSforza** [comment]
I tried it with my docker build ([in this gist](https://gist.github.com/KaiSforza/951c1d36a1b808009eb01bd1dcfb108d)) and it still errors. The output is in there, too.

**Comment by ilike2burnthing** [comment]
Thanks. Follow the same instructions I gave Drugwash2 in https://github.com/Jackett/Jackett/issues/11463#issuecomment-812937535 and let me know the results after, although I suspect this may need another look from @NinjaLikesCheez (third time lucky!)

**Comment by KaiSforza** [comment]
@ilike2burnthing Yep, I'm currently just tagging it at 815 right now and locking it there instead of using my latest tag. I'll continue to test separately though.

**Comment by NinjaLikesCheez** [comment]
Yikes. I'll try clear up some time tomorrow to investigate

**Comment by Drugwash2** [comment]
Unfortunately **0.17.841** does not fix it, at least not for me. Behavior is exactly the same. ![sad](http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/2.gif)
Tried both by upgrading from a running **0.17.815** and by manually deploying and launching.
Here's the relevant part of the log (long lists stripped, comments mine):
[Jackett_log.txt](https://github.com/Jackett/Jackett/files/6255354/Jackett_log.txt)

Would've posted the log here as text/code but this incredibly stupid GitHub system strips all CR (or LF) from the text making it a long garbled string and I don't have it in me to manually fix their stupidity.

On another note, it seems the temporary files are left over in `/tmp/...` after installation - both the unpacked folder with all files, and a copy of the compressed archive. Wasted space IMO and unfortunately I'm extremely low on free space. Does that have anything to do with the cache option on the settings page or is it something different?

**Comment by ilike2burnthing** [comment]
Thanks for letting us know. Hopefully will be resolved soon. Any updates will be posted here.

The cache setting in Jackett is for search results only.

**Comment by KaiSforza** [comment]
I've tried it with master (including [gist for anyone that wants to build it and instructions](https://gist.github.com/KaiSforza/82f1cb0cd5bb18f220b49e88b47039ce)) and it is still causing problems. I'll continue to check it with master and see if it works as commits are made or as I make changes.

Might be something to add to the azure pipeline, as well, though it only tests the linux one. (Also pretty sure it could be cleaned up and not need to do the install or clone if you just mount drives...I'm just lazy sometimes.)

**Comment by ilike2burnthing** [comment]
May be relevant:
> I don't know if the code covers this, but essentially, IMO, if the user has coded a home directory with https://github.com/Jackett/Jackett#home-directory-1 then we should be bypassing any migration processing.

https://github.com/Jackett/Jackett/issues/11313#issuecomment-813105319

**Comment by KaiSforza** [comment]
What is even supposed to be happening in this migration anyway? I can see what's going on, but why are we migrating stuff over there in the first place? At least from a linux perspective there doesn't seem to be any reason to copy things into the AppData directory. I simply did the following and suddenly Jackett works just fine.

```
diff --git a/src/Jackett.Common/Services/ConfigurationService.cs b/src/Jackett.Common/Services/ConfigurationService.cs
index d4174e86..7668c728 100644
--- a/src/Jackett.Common/Services/ConfigurationService.cs
+++ b/src/Jackett.Common/Services/ConfigurationService.cs
@@ -89,12 +89,7 @@ namespace Jackett.Common.Services
             // Perform a migration in case of https://github.com/Jackett/Jackett/pull/11173#issuecomment-787520128
             if (Environment.OSVersion.Platform == PlatformID.Unix)
             {
-                // In cases where the app data folder is the same as "$(cwd)/Jackett" we don't need to perform a migration
-                var fullConfigPath = Path.GetFullPath("Jackett");
-                if (GetAppDataFolder() != fullConfigPath)
-                {
-                    PerformMigration(fullConfigPath);
-                }
+                return;
             }
         }
```

**Comment by ilike2burnthing** [comment]
It began with an issue on MacOS - https://github.com/Jackett/Jackett/issues/10755

Fix for issue - https://github.com/Jackett/Jackett/pull/11173

Fix caused new issue - https://github.com/Jackett/Jackett/issues/11313

Fix for fix (config migration) - https://github.com/Jackett/Jackett/pull/11347

That resulted in both this issue and an issue for DietPi users, the latter of which was resolved - https://github.com/Jackett/Jackett/pull/11465

**Comment by KaiSforza** [comment]
Maybe it makes sense to have a flag or configuration directive to enable running the migration? Allow the auto-detection but also include some flag, say `--no-migration` to stop it or `--force-migration` to make it happen regardless.

**Comment by ilike2burnthing** [comment]
That should effectively be what ends up happening (in a round about fashion) with a solution based on https://github.com/Jackett/Jackett/issues/11463#issuecomment-813107882 - if XDG_CONFIG_HOME is set, do not migrate.

Config migration is only happening in edge cases anyway, because it is only purposefully set elsewhere by a few users. The problem for DietPi users was that DietPi was forcing this by default (an issue they're now going to resolve). If we skip migration for those who purposefully set it elsewhere, then that _should_ mean that it will only occur for those for who the initial fix was intended for, MacOS users (knock on wood with crossed fingers holding a 4 leaf clover).

**Comment by KaiSforza** [comment]
That's not really what it does at all, though. It checks if the AppData folder is not equal to the config path, which by default they are (unless I'm missing something) and then does the migration when they're *not* equal? Isn't that the opposite of what is supposed to happen?

**Comment by KaiSforza** [comment]
Okay sorry for all the pings but

It seems like this is specifically a problem with installing Jackett to `/Jackett` like you would normally do in a Docker container and `$HOME` is not set, making the "old" folder look like `/Jackett`. It then [tries to move everything from `/Jackett` into the `$XDG_CONFIG_HOME/Jackett` dir](https://github.com/Jackett/Jackett/blob/88ce1d96ab7cb9300e91a930185fee086590aa6a/src/Jackett.Common/Services/ConfigurationService.cs#L108) and then [deletes the contents of `/Jackett`](https://github.com/Jackett/Jackett/blob/88ce1d96ab7cb9300e91a930185fee086590aa6a/src/Jackett.Common/Services/ConfigurationService.cs#L139). 

In this situation oldDirectory is set to fullConfigPath, which for me is `/Jackett` (it runs in `/` and is the install location for the actual application). This will wipe out any install there.

**Comment by garfield69** [comment]
v0.17.848

**Comment by Drugwash2** [comment]
Confirmed fixed. Thank you very much all!
