### ISSUE TITLE
Manual search page issues

### ISSUE THREAD

**Issue by W3Warp** [Jackett/Jackett#1167]
**Windows 10 x64
Firefox x64 52.0.1 (64-bit) resolution 3840x2160
Jackett Version 0.7.1167.0**

Issues with the manual search page --> http://imgur.com/a/lh2VI
-------------------------------

**Comment by kaso17** [comment]
which firefox version are you running with which resolution?

**Comment by Blackkatt** [comment]
52.0.1 (64-bit) resolution 3840x2160

**Comment by RoloSoze** [comment]
I've always had this issue as well on Firefox (regardless of the version). I've only ever used Jackett in Firefox so I don't know about Chrome and other browsers.

The results table extends out of bounds when at least one of the search results is too long and does not get wrapped up to the next line. If, for example, you filter the search results, and the particular ones causing this issue are hidden, then the table goes back to normal. 

Maybe setting a limit for line wrapping would help with this issue?

**Comment by kaso17** [comment]
I assume in the hidden part of the results from your screenshot you've a very long release name (using . and _ instead of spaces)?
Firefox (and Chrome) won't wrap words on typical scene release punctuation causing the overflow.
I've added 14cd771f8d02e8ebf9174e91c5bab598f7afc823 to inject word wrap markers at all typical punctuation.

**Comment by RoloSoze** [comment]
In my case, this line wrapping issue tends to happen with another issue, which I believe is Firefox-specific. 

Sometimes when I search all trackers using fairly generic keywords (e.g. only the TV show's name), I'd get the following error:
![unresponsive script](https://cloud.githubusercontent.com/assets/23747425/24076253/2127f9e0-0c3d-11e7-9898-e3f1ca776823.jpg)

And when I click on Debug script, I get the following:
![debug](https://cloud.githubusercontent.com/assets/23747425/24076277/b3ed4442-0c3d-11e7-8667-a7119b741388.jpg)

Any idea what's happening? This actually happens quiet often, and when I choose to Stop Script, I can't do anything with the search results (i.e. can't sort, filter, etc.). The only thing I can do is refresh Jackett and search again using more specific keywords (e.g. adding the resolution to the search string).

**Comment by Blackkatt** [comment]
@kaso17 yes, http://imgur.com/a/mGpLr

**Comment by kaso17** [comment]
@Blackkatt your problem should be fixed with the next release.
@RoloSoze Try searching with less displayed search results (try 20). Does that make a difference?

**Comment by RoloSoze** [comment]
@kaso17 Just tried using the same keywords and 20 search results. The problem is still there. It doesn't seem to be related to the no. of search results displayed. If I make the search a bit more specific (in this case I added 1080p to the search string), the problem is gone.

**Comment by kaso17** [comment]
In the background it still adds the freeleech tags, tooltips, etc. for all rows. Seems like that's already to much in your case. Probably have to change that.

**Comment by RoloSoze** [comment]
@kaso17 Seems like it doesn't like the onloadCallback function.

**Comment by kaso17** [comment]
The onloadCallback is an unrelated warning, but fixed anyway with 02de1239aa7dd18b2b79fe12a5c7d08a15955b34

**Comment by RoloSoze** [comment]
@kaso17 Thanks for that, but how would you go about changing things to resolve this issue? What changes need to be made?

**Comment by kaso17** [comment]
There are many ways to optimize the manual search. Could start with doing the postprocessing only for the displayed results. The best option probably would be to replace the complete manual search engine with some kind of streaming (results come in for each tracker individual). But to do that properly we would need WebSockets which aren't supported by the WebServer implementation. And changing the websevrer would be a major change.

**Comment by RoloSoze** [comment]
@kaso17 I guess we could try post-processing for the displayed results & see how it goes. With Jackett now supporting way more trackers than it did a few months ago, I think improving Manual Search has become a necessity.

**Comment by allanlaal** [comment]
duplicate of  #10872 (yes. newer, since that one has a descriptive title ;) )

**Comment by garfield69** [comment]
Closing as stale.
