### ISSUE TITLE
Must install .net but I have already so many versions for x64 & x86 & rebooted

### ISSUE THREAD

**Issue by Jaladhjin** [Jackett/Jackett#11924]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Every version I could find including what JackettTray is saying is required

**.Net Version**: Every version I could find including what JackettTray is saying is required

**Jackett Version**: Can't open it to find out but I've tried the latest downloads of the installer & portable

**Last Working Jackett Version**: It totally did used to work then 1 day like a light switch just stopped on the same machine I'd always been using it on

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
If you're getting the latest installer for Jackett from [here](https://github.com/Jackett/Jackett/releases) then you're using v0.18.329 like it says there.

How are you installing .net framework? Windows 10 should update to the latest version (assuming you don't have updates disabled), so trying to manually install it would show something like `The same or a newer version is already installed`.

What is the exact error you're being presented with by JackettTray?

Type `winver` into the start menu and press enter. What are the version and build number?

Go to `C:\Windows\Microsoft.NET\Framework`, open the last folder (should be `v4.0.30319`, right-click `Accessibility.dll`, click the `Details` tab. What is the file version? Do the same thing for `clr.dll`.

If you run [sfc and dism](https://www.howtogeek.com/222532/how-to-repair-corrupted-windows-system-files-with-the-sfc-and-dism-commands/) do they find any corrupted system files?

**Comment by Jaladhjin** [comment]
winver is 20H2 OS Build: 19042.1052

I've cranked through every Windows Update & restarted a bunch trying to resolve they aren't blocked or limited in any way.

I also went into Programs & Features & enabled .Net Framework 3.5

I have Microsoft .NET SDK 5.0.204 SDK x64 & x86 installed too as well as Microsoft Windows Desktop Runtime 5.0.6 x64 & x86 as well.

When attempting to launch JacketTray gives me To run this application, you must install .NET . Would you like to download it now ?

So I'll go do that right now by hitting Yes.. which isn't taking me anywhere this time around it had directed me to the download previously. So I'm getting the files from here: https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#dependencies

So then this is all pretty confusing I end up going here: https://dotnet.microsoft.com/download/dotnet & taking .NET 5.0 (recommended)

So I grab installers for: .NET Desktop Runtime 5.0.7 & .NET Runtime 5.0.7

If I go to: C:\Windows\Microsoft.NET\Framework I see it has a few versions & goes as high as 4.0.30319

Accessibility.dll is File version is 4.8.4084.0

clr.dll is 4.8.4360.0

I'll try to run the JackettInstaller again now to see if it takes care of any dependency issue(s)

Hum interesting so the installer worked I enabled as a Service & we're all good in the hood but I can't run JackettTray from where it was on my NAS still it seems are there some specific file(s) I can put in my portable Jackett folder I have shared out to ensure these .NET files are available ?

The strangest thing is it all used to work just fine as I had it setup about a month maybe 2 ago now I'd say it stopped working with that .NET message.

**Comment by ilike2burnthing** [comment]
Bar the SDK (which you don't need), you have the same as me.

Is your NAS running Windows, and are you using the Windows installer or the binaries .zip folder?

**Comment by Jaladhjin** [comment]
I didn't know a NAS could run Windows.. that was my mistake the NAS itself is a single bay Buffalo shared with Full Access to Everyone.

The computer(s) in question attempting to run the portable Jackett stored on it are all Windows 10.

Are there file(s) I can place in my portable Jackett directory to help with the .net detection ?

**Comment by ilike2burnthing** [comment]
I can install and run Jackett in Windows Sandbox without having to install anything else, dotNET or otherwise, so you should be fine. Not really sure what happened to your system, maybe some corrupted files where eventually fixed with one of your many installs.

**Comment by Jaladhjin** [comment]
Well so even after fixing the PC itself by installing on the actual PC the files on my NAS share still do not want to run.

I can only run files off the PC itself not from my NAS share which is strange.

Agreed though it's a strange thing to have happening probably not worth the trouble if adding a few files to my NAS directory Jackett won't solve.

As in my \\nasshare\Jackett version will not load it still gives me the .net error every time despite Everyone being enabled with Full Control & Read/Write enabled.

Vs running from the PC itself works fine so I may just have to do that & abandon attempting to run from my Nas share :-(

In any case I appreciate the assistance very much thus far ! :-)

**Comment by ilike2burnthing** [comment]
If you want to run Jackett off the NAS itself, look to see if your NAS supports Docker and use the Jackett image from [LS.io](https://github.com/linuxserver/docker-jackett). Otherwise you'd have to install it natively if possible. You can't use the Windows binaries on your NAS.

**Comment by Jaladhjin** [comment]
Hum crazy alrighty thank you.

Strange part is it totally worked just fine up until recently like a light switch it just stopped 1 day insisting on those .net requirements.

Even if I copied files like those Accessibility.dll & clr.dll into the Jackett directory I'm running the portable from it wouldn't convince it files are present huh.

Well I'm glad it's working with the actual Windows setup I apologize I didn't lead with attempting to run it off my NAS truthfully I'd forgotten that important detail since I run everything off that thing & push files to it as well haha just feels like part of the computer family.

Thanks again for the assistance & advice ! 😁👍
