### ISSUE TITLE
[ImmortalSeed] "Configuration failed: " but logged in and successfully redirected

### ISSUE THREAD

**Issue by geoffgs** [Jackett/Jackett#1239]
While trying to add ImmortalSeed to a fresh jackett install in a FreeNAS jail, "Configuration failed: " is raised. No further error is generated:

![is](https://cloud.githubusercontent.com/assets/14260308/24745189/b8ee632e-1a82-11e7-9ecd-7588ba6a81c6.png)

Authentication does take place and my browser is redirected to ImmortalSeed.me. 

I've enabled advanced logging via the GUI but see nothing out of sort in logs.txt. Nothing related to indexer issues. Ignore SSL errors for troubleshooting, but using http or https as the site doesn't change the error. Added a few open trackers just fine, but ImmortalSeed is failing without cause that I can find. 

Any ideas? 

Jackett version:  0.7.1256.0
Mono version (if not using Windows): Stable 4.6.2.7/08fd525 

-------------------------------

**Comment by RoloSoze** [comment]
I'm getting the exact same problem.

**Comment by FVGAZI** [comment]
Same problem for me :(

**Comment by FVGAZI** [comment]
FWIW ImmortalSeed is working fine with Cardigann.

**Comment by badbonez** [comment]
I am having this same issue with immortalseed.me, it says configuration failed and then sends me to the immortalseed webpage.

2017-04-18 14:10:33.5357 Info   http://kjcrowley.dynu.com:8081/Admin/Dashboard 
2017-04-18 14:10:33.5362 Info DefaultHttpControllerSelector SelectController Route='action:Dashboard,controller:Admin' 
2017-04-18 14:10:33.5362 Info DefaultHttpControllerSelector SelectController Admin 
2017-04-18 14:10:33.5370 Info HttpControllerDescriptor CreateController  
2017-04-18 14:10:33.5370 Info DefaultHttpControllerActivator Create  
2017-04-18 14:10:33.5370 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2017-04-18 14:10:33.5383 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2017-04-18 14:10:33.5383 Info AdminController ExecuteAsync  
2017-04-18 14:10:33.5391 Info ApiControllerActionSelector SelectAction  
2017-04-18 14:10:33.5391 Info ApiControllerActionSelector SelectAction Selected action 'Dashboard()' 
2017-04-18 14:10:33.5403 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:33.5403 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:33.5411 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:33.5411 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:33.5411 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Dashboard()' 
2017-04-18 14:10:33.5422 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2017-04-18 14:10:33.5422 Info ApiControllerActionInvoker InvokeActionAsync Action='Dashboard()' 
2017-04-18 14:10:33.5422 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Dashboard()' 
2017-04-18 14:10:33.5435 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
Content-Type: text/html
}' 
2017-04-18 14:10:33.5435 Info ApiControllerActionInvoker InvokeActionAsync  
2017-04-18 14:10:33.5443 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Dashboard()' 
2017-04-18 14:10:33.5443 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-04-18 14:10:33.5450 Info AdminController ExecuteAsync  
2017-04-18 14:10:33.5450 Info   Content-type='text/html', content-length=31662 
2017-04-18 14:10:33.5714 Info AdminController Dispose  
2017-04-18 14:10:33.5714 Info AdminController Dispose  
2017-04-18 14:10:33.8947 Info   http://kjcrowley.dynu.com:8081/Admin/get_jackett_config?_=1492549833294 
2017-04-18 14:10:33.8953 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2017-04-18 14:10:33.8953 Info DefaultHttpControllerSelector SelectController Admin 
2017-04-18 14:10:33.8960 Info HttpControllerDescriptor CreateController  
2017-04-18 14:10:33.8960 Info DefaultHttpControllerActivator Create  
2017-04-18 14:10:33.8960 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2017-04-18 14:10:33.8972 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2017-04-18 14:10:33.8972 Info AdminController ExecuteAsync  
2017-04-18 14:10:33.8980 Info ApiControllerActionSelector SelectAction  
2017-04-18 14:10:33.8980 Info ApiControllerActionSelector SelectAction Selected action 'GetConfig()' 
2017-04-18 14:10:33.8990 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:33.8990 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:33.8990 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:33.9002 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:33.9002 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetConfig()' 
2017-04-18 14:10:33.9010 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2017-04-18 14:10:33.9010 Info ApiControllerActionInvoker InvokeActionAsync Action='GetConfig()' 
2017-04-18 14:10:33.9010 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetConfig()' 
2017-04-18 14:10:33.9024 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
2017-04-18 14:10:33.9024 Info ApiControllerActionInvoker InvokeActionAsync  
2017-04-18 14:10:33.9034 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'GetConfig()' 
2017-04-18 14:10:33.9034 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-04-18 14:10:33.9043 Info AdminController ExecuteAsync  
2017-04-18 14:10:33.9043 Info   Content-type='application/json; charset=utf-8', content-length=290 
2017-04-18 14:10:33.9057 Info AdminController Dispose  
2017-04-18 14:10:33.9062 Info AdminController Dispose  
2017-04-18 14:10:33.9325 Info   http://kjcrowley.dynu.com:8081/Admin/get_indexers?_=1492549833295 
2017-04-18 14:10:33.9332 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2017-04-18 14:10:33.9332 Info DefaultHttpControllerSelector SelectController Admin 
2017-04-18 14:10:33.9340 Info HttpControllerDescriptor CreateController  
2017-04-18 14:10:33.9340 Info DefaultHttpControllerActivator Create  
2017-04-18 14:10:33.9350 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2017-04-18 14:10:33.9350 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2017-04-18 14:10:33.9350 Info AdminController ExecuteAsync  
2017-04-18 14:10:33.9363 Info ApiControllerActionSelector SelectAction  
2017-04-18 14:10:33.9363 Info ApiControllerActionSelector SelectAction Selected action 'Indexers()' 
2017-04-18 14:10:33.9374 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:33.9379 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:33.9379 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:33.9379 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:33.9392 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Indexers()' 
2017-04-18 14:10:33.9392 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2017-04-18 14:10:33.9401 Info ApiControllerActionInvoker InvokeActionAsync Action='Indexers()' 
2017-04-18 14:10:33.9401 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Indexers()' 
2017-04-18 14:10:34.0209 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
2017-04-18 14:10:34.0320 Info ApiControllerActionInvoker InvokeActionAsync  
2017-04-18 14:10:34.0320 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Indexers()' 
2017-04-18 14:10:34.0330 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-04-18 14:10:34.0330 Info AdminController ExecuteAsync  
2017-04-18 14:10:34.0330 Info   Content-type='application/json; charset=utf-8', content-length=299799 
2017-04-18 14:10:34.3231 Info AdminController Dispose  
2017-04-18 14:10:34.3231 Info AdminController Dispose  
2017-04-18 14:10:45.5678 Info   http://kjcrowley.dynu.com:8081/Admin/get_config_form 
2017-04-18 14:10:45.5685 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2017-04-18 14:10:45.5690 Info DefaultHttpControllerSelector SelectController Admin 
2017-04-18 14:10:45.5690 Info HttpControllerDescriptor CreateController  
2017-04-18 14:10:45.5690 Info DefaultHttpControllerActivator Create  
2017-04-18 14:10:45.5704 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2017-04-18 14:10:45.5704 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2017-04-18 14:10:45.5712 Info AdminController ExecuteAsync  
2017-04-18 14:10:45.5712 Info ApiControllerActionSelector SelectAction  
2017-04-18 14:10:45.5721 Info ApiControllerActionSelector SelectAction Selected action 'GetConfigForm()' 
2017-04-18 14:10:45.5721 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:45.5733 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:45.5733 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:45.5741 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:45.5741 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetConfigForm()' 
2017-04-18 14:10:45.5750 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2017-04-18 14:10:45.5750 Info ApiControllerActionInvoker InvokeActionAsync Action='GetConfigForm()' 
2017-04-18 14:10:45.5750 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetConfigForm()' 
2017-04-18 14:10:45.5772 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
2017-04-18 14:10:45.5772 Info ApiControllerActionInvoker InvokeActionAsync  
2017-04-18 14:10:45.5784 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'GetConfigForm()' 
2017-04-18 14:10:45.5784 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-04-18 14:10:45.5793 Info AdminController ExecuteAsync  
2017-04-18 14:10:45.6402 Info   Content-type='application/json; charset=utf-8', content-length=968 
2017-04-18 14:10:45.6414 Info AdminController Dispose  
2017-04-18 14:10:45.6421 Info AdminController Dispose  
2017-04-18 14:10:56.6636 Info   http://kjcrowley.dynu.com:8081/Admin/configure_indexer 
2017-04-18 14:10:56.6642 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2017-04-18 14:10:56.6642 Info DefaultHttpControllerSelector SelectController Admin 
2017-04-18 14:10:56.6650 Info HttpControllerDescriptor CreateController  
2017-04-18 14:10:56.6650 Info DefaultHttpControllerActivator Create  
2017-04-18 14:10:56.6650 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2017-04-18 14:10:56.6661 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2017-04-18 14:10:56.6661 Info AdminController ExecuteAsync  
2017-04-18 14:10:56.6661 Info ApiControllerActionSelector SelectAction  
2017-04-18 14:10:56.6673 Info ApiControllerActionSelector SelectAction Selected action 'Configure()' 
2017-04-18 14:10:56.6680 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:56.6680 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-04-18 14:10:56.6680 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:56.6692 Info HttpActionBinding ExecuteBindingAsync  
2017-04-18 14:10:56.6692 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()' 
2017-04-18 14:10:56.6700 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2017-04-18 14:10:56.6700 Info ApiControllerActionInvoker InvokeActionAsync Action='Configure()' 
2017-04-18 14:10:56.6700 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()' 
2017-04-18 14:10:56.6717 Debug IWebClient.GetString(Url:http://immortalseed.me/takelogin.php) 
2017-04-18 14:10:56.6722 Debug UnixLibCurlWebClient: Posting username=badbonez&password=baddestbonez 
2017-04-18 14:10:57.1697 Debug IWebClient: Returning OK => 
	<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<html lang="en">
		<head>
			<title>immortalseed.me</title>
			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			<meta http-equiv="refresh" content="2;URL=https://immortalseed.me/index.php?logged=true" />
			<link rel="stylesheet" type="text/css" href="https://immortalseed.me/style.php?theme=default&style=style.css" />
		</head>
		<body>
			<div style="margin: auto auto; width: 50%; padding-top: 10px;" align="center">
				<table border="0" cellspacing="0" cellpadding="4" class="tborder">
					<tr>
						<td class="thead"><strong><a href="https://immortalseed.me">immortalseed.me</a></strong></td>
					</tr>
					<tr>
						<td class="trow1" align="center"><p>You have successfully logged in...</p></td>
					</tr>
					<tr>
						<td class="trow2" align="right"><a href="https://immortalseed.me/index.php?logged=true" class="smalltext">Click here if you don't want to wait any longer.</a></td>
					</tr>
				</table>
			</div>
		</body>
	</html> 
2017-04-18 14:10:57.1719 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
2017-04-18 14:10:57.1725 Info ApiControllerActionInvoker InvokeActionAsync  
2017-04-18 14:10:57.1730 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()' 
2017-04-18 14:10:57.1730 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-04-18 14:10:57.1730 Info AdminController ExecuteAsync  
2017-04-18 14:10:57.1741 Info   Content-type='application/json; charset=utf-8', content-length=1814 
2017-04-18 14:10:57.1741 Info AdminController Dispose  
2017-04-18 14:10:57.1753 Info AdminController Dispose

**Comment by kaso17** [comment]
They changed the login procedure slightly, fixed with b002220cc3b1c1e66964801a9f8713c87e71dbea

**Comment by geoffgs** [comment]
Hi kaso17,

Timestamps suggest that b002220 was included in the 0.7.1296.0 release. Performed a manual update and configuring ImmortalSeed no longer redirects, but configuration still fails

![immortal](https://cloud.githubusercontent.com/assets/14260308/25238322/1bddf1d2-25bb-11e7-93d4-9113eaefc7e6.png)

**Comment by kaso17** [comment]
The change isn't released in a binary build yet.
