### ISSUE TITLE
All torrents failing tests

### ISSUE THREAD

**Issue by chrishiam** [Jackett/Jackett#1277]
Jackett version:  v0.7.1287
Mono version (if not using Windows):  4.8.0
Log File: https://pastebin.com/3LiuLxnU

-------------------------------

Recently all my added indexers have begun to fail. I updated both Jackett and Mono to the latest versions to make sure that wasn't the issue and it's persistent. I'm using public trackers, but when I try to add private trackers (i.e. torrentleech) it doesn't let me add them.

From what I can tell it's some kind of SSL issue? The command I'm using to launch Jackett is:

`screen -dmS jackett mono --debug ~/Jackett/JackettConsole.exe --SSLFix true --IgnoreSslErrors true -t -1`

I've also tried:

`screen -dmS jackett mono --debug ~/Jackett/JackettConsole.exe`

and:

`screen -dmS jackett mono ~/Jackett/JackettConsole.exe`

Lastly, I've found since installing that Jackett is continuously crashing and I have to manually restore the screen.

**Comment by flightlevel** [comment]
What OS?
Have you tried https://github.com/Jackett/Jackett/issues/1179

**Comment by chrishiam** [comment]
@flightlevel I'm on `Debian GNU/Linux 8.7 (jessie)`. I just tried running `wget https://curl.haxx.se/ca/cacert.pem && cert-sync cacert.pem` but nothing changed even after restarting Jackett, although I was getting the following error when running the command:

> System.UnauthorizedAccessException: Access to the path "/usr/share/.mono" is denied.

Unfortunately I have no sudo access.

**Comment by corpseas** [comment]
Downgrade mono to 4.6.2, I just fixed this issue myself as of a few hours ago. Apparently there's some SSL issue with Jackett and mono 4.8.0

**Comment by flightlevel** [comment]
@chrishiam 

What sort of CPU are you running?

Can you confirm you've installed both `mono-devel` and `ca-certificates-mono`

Try
`cert-sync`
and report version

Try from a directory you have write access eg. Downloads
`wget https://curl.haxx.se/ca/cacert.pem`
`cert-sync --user ./cacert.pem`
You should have access to do this without sudo and report results/try Jackett

Or even try (don't have to download anything)
`cert-sync --user /etc/ssl/certs/ca-certificates.crt`

Do you get html or an error from running
`csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'
`

You can also try running Jackett with
`mono JackettConsole.exe -c libcurl`

Or via docker

**Comment by chrishiam** [comment]
@corpseas tried downgrading to `Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Sat 15 Apr 13:12:42 UTC 2017)` but no luck, issue still exists.

@flightlevel I'm going to try these as a type this message out and report back, hopefully it'll help other people having this issue.

`cert-sync`: `Linux Cert Store Sync - version 4.6.2.0`

Imported `cert-sync` as suggested, import successful but still all tests fail.

No errors at all when running `csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'`

Running `mono JackettConsole.exe -c libcurl` actually gets some success with all tests working. In fact, attaching this to a screen fixes the problem entirely. So there we have it! Something in the above worked ;-)

**Comment by DGCupit** [comment]
Hey, thanks very much for his solution. My Jackett just started failing on all connections, after having worked fine for months. I followed all the suggestions and changed my service to start with the  -c libcurl option and all connections are now working.
