### ISSUE TITLE
[req]: Swarmazon has added a search api

### ISSUE THREAD

**Issue by protocolprowler** [Jackett/Jackett#13725]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello wizards of Jackett. 

Swarmazon added a search API a while ago but it was strictly limited to aiding dup prevention for an upload API. We just finished enhancing our search API for what we believe should be required for Jackett searches. If we've missed anything you require please let us know and we'll fix it promptly. 

As time allows please add a second Swarmazon connection option in Jackett that uses our API. Usage details are listed in solution. 

Thanks in advance for your time and for maintaining the best search app on the web. 

### Describe the solution you'd like

Example search by Name:
https://swarmazon.club/api/search.php?api_key=YOURAPITOKEN&filter=WHATYOUSEEK

Example search by Media Reference:
https://swarmazon.club/api/search.php?api_key=YOURAPITOKEN&media_ref=IMDBorSTEAMID

You can also combine filter & media_ref if needed. Search results will be returned in JSON key pairs which now include       uploaderid,username,name,size,seeders,leechers,completed,hash,upload_timestamp,ref_id,categoryid,category_name,typeid,type_name,freeleech,download(link),torrent(link) and media(link).

**Comment by garfield69** [comment]
an item for your consideration:
- we often use a keywordless search to return the latest torrents, however if we use 
`https://swarmazon.club/api/search.php?api_key=YOURAPITOKEN&filter=`
we receive every torrent (currently 8990) :-) which is obviously a burden on your server and more than most users expect to get on a query.
So I suggest implementing a **limit=** parm, and  if a limit is not specified on the query then default to **limit=100**, which is what most *arr apps expect to receive for a query.

**Comment by protocolprowler** [comment]
Thanks for the feedback and prompt response 😄. We'll shoot for getting both these items implemented in the next 12-24 hours.

**Comment by protocolprowler** [comment]
@garfield69 An update adding an enforced record limit, media_poster and media_genre has been published. Adding the poster slows results _slightly_ because our cached json needs decoded. 

Hoping your hover tool can provide static resizing? It would be nice to lock width at about 100px to make our poster links approx the same size as what is seen on Unit API searches. 

Thanks.

**Comment by garfield69** [comment]
v0.20.2267

**Comment by ilike2burnthing** [comment]
@protocolprowler following up on https://swarmazon.club/forum/d/76-api-issue, if there are any changes which need to be made to our use of your API, let us know:

https://github.com/Jackett/Jackett/blob/a3f0bd5b8738a1e5f3be7b461c14154239f57500/src/Jackett.Common/Definitions/swarmazon-api.yml#L49-L59

For a keywordless search (what automation like Sonarr et al. would use for RSS sync):
`https://swarmazon.club/api/search.php?api_key=API_KEY&filter=&limit=100`

As for you finding that the issue started on January 23rd, I don't see anything relevant [around then](https://github.com/Jackett/Jackett/releases?page=4), but our Swarmazon HTML scrapper was [removed ~2wks previous](https://github.com/Jackett/Jackett/commit/4521fceae4a94abe57317be33dece3f926311cac), so maybe a delayed effect from people gradually switching over to the API indexer.

**Comment by protocolprowler** [comment]
@ilike2burnthing I've published some minor adjustments to the Swarm search API. If should now correctly process filter-less calls. To keep things responsive your results will be limited to uploads from the last 7 days. 

Your thoughts and feedback are welcomed. 

Thanks.

**Comment by ilike2burnthing** [comment]
Working well, still getting 100 results so no issues here. Many thanks.

**Comment by ilike2burnthing** [comment]
Forgot why I was even looking in the first place! Would you be able to add a `freeleech` variable where, for example, `0` would return all results and `1` would return only freeleech results (and if you want `2` would return non-freeleech, but we wouldn't use it)?

**Comment by protocolprowler** [comment]
Hey, I finally got around to publishing a beta of the freeleech only API
option. You should be able to start testing now.

Currently, its just doing an empty check on the 'freeleech' var so it
doesn't matter value you send. If its helpful to have a non- freeleech
toggle ill add specific value checks for it, I'm thinking 0 for non-FL only
and 1 for FL only.

Let me know what you think.

Thanks.

**Comment by ilike2burnthing** [comment]
Yep, that's working well, thanks again!

Just changed the inputs to:

```yml
  inputs:
    api_key: "{{ .Config.apikey }}"
    filter: "{{ .Keywords }}"
    media_ref: "{{ if .Query.IMDBID }}{{ .Query.IMDBID }}{{ else }}{{ end }}"
    freeleech: "{{ if .Config.freeleech }}1{{ else }}{{ end }}"
    limit: 100
```

If the user configures the indexer to `search freeleech only` then it will send `freeleech=1`, otherwise it won't send anything (same as `media_ref`).

We wouldn't use a 'non-freeleech only' search, but by all means add it for others to make use of.

Do you want us to hold off on implementing it, or should we add it now? The next build won't be published until roughly this time tomorrow.

**Comment by protocolprowler** [comment]
Glad to hear it! By all means go ahead and add it at your convenience.

Thanks for staying in touch, always pushing for improvement and keeping
Jackett great!

**Comment by garfield69** [comment]
v0.20.3949
