### ISSUE TITLE
[thepiratebay] (testing) Exception (thepiratebay): certificate validation failed: [Subject]  CN=apibay.org[Issuer]  CN=E1, O=Let's Encrypt, C=US[Serial Number]  04DE609F32FD352FA5C582011D6BFC16074D[Not Before]  4/27/2023 1:45:18 AM[Not After]  7/26/2023 1:45:17 AM[Thumbprint]  7CE4DC13187DCB63E3FB3A4C845FDD37069F8331: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by namanix** [Jackett/Jackett#14311]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-05-07 08:18:11	Info	Using HTTP Client: HttpWebClient2
2023-05-07 08:18:11	Info	Using FlareSolverr: No
2023-05-07 08:18:11	Info	Using proxy: Disabled
2023-05-07 08:18:11	Info	App config/log directory: /volume1/@appstore/jackett/var/.config/Jackett
2023-05-07 08:18:11	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-05-07 08:18:11	Info	Running in Docker: No
2023-05-07 08:18:11	Info	Jackett variant: CoreLinuxAmdx64
2023-05-07 08:18:11	Info	OS version: Unix 4.4.59.0 (64bit OS) (64bit process)
2023-05-07 08:18:11	Info	Environment version: 6.0.16 (/volume1/@appstore/jackett/share/)
2023-05-07 08:18:10	Info	Starting Jackett v0.20.4101
```

### Description

1) Add the piratebay as an indexer on jacket
2) Click test to see if it works

Sorry this is my first time submitting a ticket like this. It just seems that there is something wrong with the SSL certificate of apibay.org on my NAS. 

What can I do to resolve this as I can open the page in my browser without a problem.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (thepiratebay): certificate validation failed: [Subject]
  CN=apibay.org

[Issuer]
  CN=E1, O=Let's Encrypt, C=US

[Serial Number]
  04DE609F32FD352FA5C582011D6BFC16074D

[Not Before]
  4/27/2023 1:45:18 AM

[Not After]
  7/26/2023 1:45:17 AM

[Thumbprint]
  7CE4DC13187DCB63E3FB3A4C845FDD37069F8331
```

### Screenshots

![image](https://user-images.githubusercontent.com/1583377/236661357-339f0c43-7752-4282-9bf5-559cbfd1f790.png)

**Comment by garfield69** [comment]
what specific flavour of NAS are you running?

**Comment by namanix** [comment]
Synology DS220+
DSM 6.2.3

**Comment by ilike2burnthing** [comment]
The mono fix for Synology users was - https://github.com/Jackett/Jackett/issues/7237#issuecomment-592222874

Though as you're using .NET, try - https://github.com/Jackett/Jackett/issues/12341#issuecomment-971888686

Let us know if it works for you so we can update the wiki.

**Comment by soggychips** [comment]
I don't think this is a NAS problem, as I'm seeing the same error only for piratebay and no other indexers in jackett.. Was working totally fine until about a week ago

**Comment by namanix** [comment]
Exactly this soggychips. I wanted to test the fixes mentioned. Have you done so?

**Comment by ilike2burnthing** [comment]
Easy way to find out.

**Comment by soggychips** [comment]
Update: Now seeing this for multiple indexers. 1337x, bitru, rarbg, and more. 

Not using a NAS..

Able to curl all of the domains no problem.

**Comment by ilike2burnthing** [comment]
Should be a similar process to what's linked above; I'd assume the only difference would be removing `&& synoservice --restart DSM` from the end of the commands, though you may want to look into that more yourself. If it works for you, let us know.

**Comment by soggychips** [comment]
I'm not sure how the above mentioned fixes would solve anything for my case... I stood up jackett on a completely different server just now and the same exact problem exists there too

**Comment by soggychips** [comment]
New certs did nothing. Same results.

**Comment by ilike2burnthing** [comment]
If you don't use a proxy/VPN are you DNS blocked, or can you test Jackett like that?

**Comment by garfield69** [comment]
It seems that the CA that are causing trouble are all Let's Encrypt E1 certificates that were issued around the last week of April and the first two weeks of May.
OpenSSL may have trouble verifying these CA on certain platforms. Research is ongoing.

**Comment by gingerbeardman** [comment]
Hey jackettbot, I'm still getting this.

**Comment by ilike2burnthing** [comment]
Have you followed the steps linked and discussed above?

**Comment by gingerbeardman** [comment]
My certificate store is up-to-date as I have it update them on a regular schedule. But, just for kicks, I did it again using the issue link and the issue persists. 

![Screen shot 2023-06-14 at 15 41 45](https://github.com/Jackett/Jackett/assets/49612/f6782a27-e1a5-4a31-8dad-084a18929d08)

![image](https://github.com/Jackett/Jackett/assets/49612/db750ceb-4d4b-451c-86ec-56b28fc06831)

So, @ilike2burnthing, I think it's time to stop recommending those steps as they have nothing to do with this particular  issue.

This issue is about validation of the cert being served by `apibay.org` (and other recent Let's Encrypt certs from April & May). Hence my question to @garfield69 who said research was ongoing into what is actually going on here.

**Comment by namanix** [comment]
Sorry for not responding for such a long time. No the problem is not solved yet. Although at this point I'm just looking for a way to start Jackett with IgnoreSslErrors=true. It solves the issue for me at least in SSH modus. But I have no clue how to add IgnoreSslErrors=true to the startup command on the DSM package manager. Does anyone have a solution for this? How can I start jackett on a synology NAS using that startup argument.

**Comment by ilike2burnthing** [comment]
@namanix have you tried running Jackett in Docker rather than native?

**Comment by namanix** [comment]
Yeah I tried. On 2 NAS systems I tried downloading the docker via the Docker tool in DSM.
It times out on both my NAS systems. 1 on DSM 6.x and 1 on the latest DSM. Which is weird.

If you have a different way to download Jackett as a docker for me I'm all ears! :D

**Comment by ilike2burnthing** [comment]
As in even downloading the Jackett Docker image times out, or accessing the Jackett container times out, or testing TPB in the running Jackett container times out?

**Comment by namanix** [comment]
Sorry that really was a next level terrible explanation from my side. Downloading the Jackett Docker image just times out. And I have no way to see why it does. Can I download it any other way? I want to start moving to docker soon. Same goes for Sonarr. But this first haha

**Comment by ilike2burnthing** [comment]
Can you download any Docker images? If so, try Portainer and use it to manage your containers (e.g. Jackett) instead.

**Comment by namanix** [comment]
Yeah other images no problem. I do see on the "Image" tab that I can download by url. Any url I can try?

**Comment by ilike2burnthing** [comment]
Not that I'm aware of. Have you tried both `lscr.io/linuxserver/jackett` and `docker.io/linuxserver/jackett`?

Any luck using Portainer instead of DSM's Docker manger?

**Comment by gingerbeardman** [comment]
FWIW I also am unable to retrieve the linuxserver/jackett docker image through Synology DSM Docker app ("loading..." and then 60 seconds later "operation timed out"), but was able to download it through Portainer-CE (an alternate docker manager, installed through Synology Docker app). You could also try the command-line, though I did not get to that point. 

I don't use Jackett through docker, but I did this to provide a data point for you @namanix

**Comment by ilike2burnthing** [comment]
Very odd, might be worth bringing up with Synology support.

**Comment by namanix** [comment]
Okay update. I have Jackett up and running in docker. Downloaded the image via Portainer and started the container in DSM. Added the IgnoreSslErrors to my startup and ThePirateBay works again. It still is strange and I do think this should be solved in a different way. But for now I have a working setup! Thank you!

**Comment by ilike2burnthing** [comment]
Was TPB still failing with the same error in the dockered Jackett without `IgnoreSslErrors`?

**Comment by namanix** [comment]
Hmmmm.... Weirdly no. Just tested it. I should have tested that before adding that startup argument.

**Comment by ilike2burnthing** [comment]
K, if it's working in Docker on the same device then there's some sort of host dependency causing the issue, presumably OpenSSL. Run `openssl version` on the host.

**Comment by gingerbeardman** [comment]
FWIW, mine on Synology 6.2.3 is `OpenSSL 1.0.2u-fips  20 Dec 2019`

I do plan to update my system but I need to be physically at it which I won't be for a while.

**Comment by ilike2burnthing** [comment]
According to DSM release notes, OpenSSL has been updated several times since v7.0 - https://www.synology.com/en-us/releaseNote/DSM (1.1.1l > 1.1.1o > 1.1.1t > 3.0.7)

**Comment by gingerbeardman** [comment]
Right, I will upgrade to latest 7.x asap

**Comment by shawn8888** [comment]
> 

@namanix You said:
“added the IgnoreSslErrors=true cli flag to the jacket launcher (Jackett/jackett_launcher.sh)”
Would you kindly tell me how to do this in a Docker Container?
I am using Synology DSM 6.1.7 and I cannot upgrade it to 7.

**Comment by gingerbeardman** [comment]
How is everybody else doing with this one?

Still busted for me even after the recent cert renewal at apibay.org

**Comment by ilike2burnthing** [comment]
Had a chance to update DSM?

**Comment by gingerbeardman** [comment]
Nope, still travelling.

**Comment by namanix** [comment]
Comment to re-open

**Comment by gingerbeardman** [comment]
I just bit the bullet and migrated my Jackett and Radarr from synology packages to docker. 

- Jackett: required manual migration of indexers, settings and API key (10 minutes)
- Radarr: restore backup, make sure new container uses same pair of ports, and map config/movies/downloads drives

Unsubscribing from this issue.

So long and thanks for all the ssh.

**Comment by shawn8888** [comment]
Not sure what happened. I tested thepiratebay today and it's working again.
I guess the certificate issue was resolved on the server side.

**Comment by ilike2burnthing** [comment]
While it has been updated, it's still an E1 cert. There was no issue to resolve server side.
