### ISSUE TITLE
[romanianmetaltorrents] (testing) Exception (romanianmetaltorrents): Relogin failed: Parse error

### ISSUE THREAD

**Issue by Wolf666** [Jackett/Jackett#14773]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-10-17 08:57:25.3671 Info Starting Jackett v0.21.1025
2023-10-17 08:57:26.5103 Info Environment version: 6.0.23 (/app/Jackett/)
2023-10-17 08:57:26.5245 Info OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
2023-10-17 08:57:26.5260 Info Jackett variant: CoreLinuxMuslAmdx64
2023-10-17 08:57:26.5260 Info File /etc/issue: Welcome to Alpine Linux 3.18
2023-10-17 08:57:26.5260 Info Running in Docker: Yes (image build: v0.21.1025-ls191)
2023-10-17 08:57:26.5284 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-10-17 08:57:26.5284 Info App config/log directory: /config/Jackett
2023-10-17 08:57:26.5301 Info Using proxy: Disabled
2023-10-17 08:57:26.5301 Info Using FlareSolverr: No
2023-10-17 08:57:26.5325 Info Using HTTP Client: HttpWebClient2
2023-10-17 08:57:26.5478 Info Loading Native indexers ...
2023-10-17 08:57:26.7006 Info Loaded 73 Native indexers.
2023-10-17 08:57:26.7061 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2023-10-17 08:57:29.2664 Info Loaded 521 Cardigann indexers.
2023-10-17 08:57:29.2664 Info Loaded 594 indexers in total
```

### Description

Fail to test

### Logged Error Messages

```text
2023-10-17 08:48:02.2640 Error Jackett.Common.IndexerException: Exception (romanianmetaltorrents): Login failed: Selector "a[href="logout.php"]" didn't match

[v0.21.1025.0] Jackett.Common.IndexerException: Exception (romanianmetaltorrents): Login failed: Selector "a[href="logout.php"]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by Wolf666** [comment]
Full log
[log.txt](https://github.com/Jackett/Jackett/files/12925391/log.txt)

**Comment by garfield69** [comment]
When you use the jackett dashboard to edit the config, does that page display the Captcha Image of the 6 digit code you need to enter in the Captcha Text box?

**Comment by Wolf666** [comment]
> When you use the jackett dashboard to edit the config, does that page display the Captcha Image of the 6 digit code you need to enter in the Captcha Text box?

Yes, when I configure I see the 6 digit captcha, I put that number on the captcha text box.

**Comment by garfield69** [comment]
OK. I see that the indexer is out of date with the login page, so I can fix that part.
But this still leaves the fact that when you enter the correct code along with your credentials you are not login in successfully.

Unfortunately, the log you provided has only captured the events of the TEST indexer you did, which tried to autologin and fails because the security code is not entered.

What I need you to do is to turn on the enhanced logging again, and use your Jackett dashboard to edit the indexer and fill in the security code and click OKAY.
Please try not to do any other indexer activity, its very difficult to separate the events when 1337x and RockBox are interleaved amongst the events of your RMT activity.
Then post that fresh enhanced log so I can hopefully see what happens during an actual indexer config login rather than a indexer TEST.
Thanks.

**Comment by Wolf666** [comment]
Done, here the log 
[log.txt](https://github.com/Jackett/Jackett/files/12926146/log.txt)

**Comment by garfield69** [comment]
So that looks like a successful login to me.
Can you not now use the dashboard to use the indexer to search and get results?
And does the indexer TEST still fail?

**Comment by Wolf666** [comment]
> So that looks like a successful login to me. Can you not now use the dashboard to use the indexer to search and get results? And does the indexer TEST still fail?

Yes, it shows a successful login but test button is red and ask for captcha again. Manual search does not work. Lidarr cannot add the traker as well.
[log.txt](https://github.com/Jackett/Jackett/files/12926341/log.txt)

**Comment by garfield69** [comment]
Looking a little closer to the login attempt earlier I see that after login the indexer was redirected to the rules page.
If you login to the web site, does that happen to you also?
Do you need to accept the rules by clicking on a button somewhere before you can access the browse torrents page/

**Comment by Wolf666** [comment]
When I log the website, it asks for credential and captcha, then it redirect to rules page but without any action I mean I don't have to accept rules.
I am under VPN, my PC use a fixed IP while NAS (where Jackett is running) use a gateway pool (several IPs on a balanced roundrobin multiwan).
When logging in the website, if I change my IP it asks for login again, I need to put credential and captcha again.

**Comment by garfield69** [comment]
v0.21.1043
let me know how you go with this one.
You should start by doing a new captcha pull with the config edit, then try a TEST and a search.

**Comment by Wolf666** [comment]
> v0.21.1043 let me know how you go with this one. You should start by doing a new captcha pull with the config edit, then try a TEST and a search.

Great! Everything is working, included Lidarr. Nice job. thanks.
