### ISSUE TITLE
TorrentNetwork Fix?

### ISSUE THREAD

**Issue by STX2k** [Jackett/Jackett#1482]
Hello, 

the TNTracker has a new Source and the index Plugin doesnt work anymore. Can you fix the Index Plugin?

https://tntracker.org

Greets STX

**Comment by kaso17** [comment]
They completely replaced the tracker software with something I haven't seen before.
It needs to be completely re-implemented.

**Comment by kaso17** [comment]
finally had time for this
fixed with 767521409248e3f5558fa1cb487a5d6e12f69b3a

**Comment by hannesschmidt** [comment]
Still not completly fixed. I am able to search but download is not possible. It says HTTP Error 404.
