### ISSUE TITLE
[speedcd] (updating) Exception (speedcd): Error parsing the login form: Error parsing the login form

### ISSUE THREAD

**Issue by norbsmaq** [Jackett/Jackett#15164]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://server_url:8191
Using proxy: Disabled
App config/log directory: /home/user/.config/Jackett
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.150 (64bit OS) (64bit process)
Environment version: 6.0.28 (/opt/Jackett/)
Starting Jackett v0.21.2069
```

### Description

Speed.cd started failing over the weekend.  At first I thought it was my Flaresolverr that was broken because I was getting the time out from that.  After upgrading Flaresolverr I am now seeing the "Error parsing the login form" error.  I saw another post on here that suggested using email instead of username, however that made no difference with this problem.  I get the error whether or not I use username or email.

### Logged Error Messages

```text
System.Exception: Error parsing the login form

[v0.21.2069.0] System.Exception: Error parsing the login form
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in ./Jackett.Common/Indexers/SpeedCD.cs:line 136
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/SpeedCD.cs:line 121
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
the login has been changed. It now has different two step path. 
while I changed the paths, It still fails for me, so clearly I'm not up to the task of updating this one.
Needs a proper C# dev to fix.

**Comment by garfield69** [comment]
sorted. I did use the correct new paths, but in earlier testing it was not working, but I tried it again just now and its working fine.
Don't know but I thing earlier I was getting a cloudflare are-you-human which may have thrown things off.

**Comment by garfield69** [comment]
v0.21.2090

**Comment by garfield69** [comment]
Well this is beyond me ATM, the login fails when cloudflare are-you-human gets invoked for Jackett sometimes.
I have not seen that challenge when using the browser, so I don't know what needs to be some to make this work other that going to the cookie method?

**Comment by garfield69** [comment]
@ilike2burnthing  maybe this needs https://github.com/FlareSolverr/FlareSolverrSharp/pull/31 ?

**Comment by ilike2burnthing** [comment]
FlareSolverrSharp updated - https://github.com/Jackett/Jackett/commit/e5521678bfa3f30bf2276db691f7c1dd5c6bc8e5 (thank you @highfredo)

This resolves one issue with Speed.CD - when already configured and running a test FlareSolverr would solve the challenge but Jackett would error out, yet the next test (and all subsequent tests) would be successful.

However, I think there may be an indexer issue as well, as when trying to add for the first time or reconfigure, Jackett errors out. When running FlareSolverr with `headless=false` I see that before the challenge the browser opens with the following in the URL bar and displaying a textbox with my username:

```html
data:text/html;charset=utf-8,%0A        <!DOCTYPE html>%0A        <html>%0A        <body>%0A            <form id="hackForm" action="https://speed.cd/login" method="POST"><input type="text" name="username" value="REMOVED"><br></form>%0A            <script>document.getElementById('hackForm').submit();</script>%0A        </body>%0A        </html>
```

Once the challenge is solved, it's just the blank username login page.

**Comment by garfield69** [comment]
While we wait for a possible solve, I've adapted the indexer for cookie login. Should I add it as an alternative to the existing indexer or as a replacement?

**Comment by garfield69** [comment]
I've adapted the indexer for cookie login. and added id as speed.cd(cookie) as an alternative.

**Comment by garfield69** [comment]
v0.21.2103

**Comment by norbsmaq** [comment]
> I've adapted the indexer for cookie login. and added it as speed.cd(cookie) as an alternative.

Cookie version is working for me.  The other one is still not working, but based on the comments here I think that is expected.

Thank you!!

**Comment by ilike2burnthing** [comment]
If Speed.CD is already configured it should be working now, it's only adding or reconfiguring which won't.

**Comment by norbsmaq** [comment]
> If Speed.CD is already configured it should be working now, it's only adding or reconfiguring which won't.

I had removed the Indexer during troubleshooting so I had to reconfigure it.  The regular one was still failing so I removed and added the cookie version.

**Comment by wilotas** [comment]
Hi guys, 

I have been checking jackett service "availabity" during last 2 years using a simple "Uptime Kuma" process checking http url. Until yesterday it was working perfectly but from last night docker image update I receive a 400 error message so I can not check it. 

Could be related with the error mentioned above? I do not know If I can change something in the simple http request I do from Uptime Kuma.

**Comment by ilike2burnthing** [comment]
Are you just checking Jackett itself (e.g. something like `http://192.168.0.42:9117`), or specifically the Speed.CD Jackett indexer API endpoint?

**Comment by wilotas** [comment]
> Are you just checking Jackett itself (e.g. something like `http://192.168.0.42:9117`), or specifically the Speed.CD Jackett indexer API endpoint?

Directly to: http://jackettcontainerip:9117 as I have been doing during las 2 years, nothing changed.

Thanks @ilike2burnthing

**Comment by ilike2burnthing** [comment]
I don't see how it would be related to this. Open a new issue and provide the information requested.

**Comment by norbsmaq** [comment]
Cookie version has started failing today.  See https://github.com/FlareSolverr/FlareSolverr/issues/1129

**Comment by norbsmaq** [comment]
User Agent string seems to have fixed the cookie version of this tracker for me, for now.  Thank you!

**Comment by garfield69** [comment]
based on what information?

**Comment by garfield69** [comment]
never mind, I see the update. I'll test and action.

**Comment by garfield69** [comment]
v0.21.2199
