### ISSUE TITLE
[req]: Polskie-Torrenty

### ISSUE THREAD

**Issue by gekomod** [Jackett/Jackett#15712]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: Polskie-Torrenty
- URL: https://polskie-torrenty.eu/
- Description: Polskie-Torrenty is a POLISH Semi-Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
I was making good progress writing the indexer, but during testing to fix coding bugs, I appear to have ended up being denied access
I see:
```
error	
[403] Forbidden : Dostęp zabroniony
 	Zapytanie odrzucone przez serwer. Nie masz dostępu do /login.php na tym serwerze.
 	 
 	You don't have permission to access /login.php
```

just me?

**Comment by garfield69** [comment]
maybe everyone. uptime shows 403 for all 43 checkpoints so it looks like the site may have crashed ;-(

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
v0.22.950

**Comment by garfield69** [comment]
https://polskie-torrenty.eu/ > cloudflare  Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15712#issuecomment-3391165329

**Comment by ilike2burnthing** [comment]
- Working for me, but 6 Uptrends checkpoints time out
- now 8/43 > 522

**Comment by garfield69** [comment]
posted on the site 9th Dec 2025

The website is in redevelopment / modernization - we apologize for the problems (disappearing or incorrectly displayed departments, temporary change of the layout of the page) - please be patient. 

this morning indexer failed with invalid release title missing.
I haven't checked what layout change has occurred yet.

**Comment by garfield69** [comment]
OK, new design no longer has a download link href, and neither has the details page as far as I can tell.
So the title name was previously fetched from the download link filename, but that is not available hence the indexer failing with  invalid release title missing.
It looks like the torrent meta its now being fetched via JS, we will need to see if the source is available to look at, to determine if it can be used by indexer.
Otherwise we will just delete the indexer and call it a day.

**Comment by ilike2burnthing** [comment]
Details link is:

> /details.php?id=abcdef123456

Download link is:

> /download.php?torrent=abcdef123456

So it shhhhhould [knocks on wood] be as simple as replacing `details.php?id` with `download.php?torrent`, or pulling the `id` and plonking it on the end of `/download.php?torrent=` - dealer's choice ;)

**Comment by garfield69** [comment]
https://polskie-torrenty.eu/wyszukaj.php > 
```
[v0.24.512.0] System.InvalidOperationException: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.
 ---> System.ArgumentException: 'utf8mb4' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   at System.Net.Http.HttpContent.ReadBufferedContentAsString()
   at System.Net.Http.HttpContent.<>c.<ReadAsStringAsync>b__36_0(HttpContent s)
   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
```

**Comment by ilike2burnthing** [comment]
Happened previously with the login page - https://github.com/Jackett/Jackett/issues/15835

I've used the contact form this time, rather than directly messaging the owner, we'll see if that has any better luck.

**Comment by ilike2burnthing** [comment]
Bug resolved by staff

Uptrends also shows all checkpoints successful.

**Comment by lukjod** [comment]
still a problem with finding login page
`Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://polskie-torrenty.eu/login.php using form selector form[name="login"]

[v0.24.739.0] Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://polskie-torrenty.eu/login.php using form selector form[name="login"]
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 619
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1080
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26`

**Comment by ilike2burnthing** [comment]
Form name was removed, but they've added an embedded CF challenge, so after all that we're gonna have to change to cookies login instead.

**Comment by garfield69** [comment]
v0.24.752

**Comment by garfield69** [comment]
https://polskie-torrenty.eu/ > Error code: 500 Internal Server Error

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://polskie-torrenty.eu/ > TCP Connection Error

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
- https://polskie-torrenty.eu/ > TCP Connection Error
closed in error, still down from 3 days ago
- DNS Lookup Error
