### ISSUE TITLE
Query to search for season packs if a season is finished 

### ISSUE THREAD

**Issue by king8084** [Jackett/Jackett#1813]
Hello

so most trackers delete single eps when season is done, and when you search sonarr for eps, nothing will show up since jackett is searching for single eps

can you make it search for a season even when you looking for a single ep if the season in full is there? i talked to sonarr developer and he says this needs to be done within jackett

**Comment by kaso17** [comment]
Jackett doesn't know if a season ended.
Sonarr does. That's why I would expect this feature on the sonarr side.
On the Jackett side we could implement only a stupid "repeat search only for season if a search for episode didn't return any results" mode. But that would cause unnecessary additional load on the tracker.
Where did you discuss this with the sonarr devs? Is there an sonarr issue about this?

**Comment by king8084** [comment]
yes
https://github.com/Sonarr/Sonarr/issues/2166

we talked a bit more about it through PMs in sonarr forum, his final comment is that he will not implement this through sonarr

the issue is, most trackers dont work for sonarr through jackett since they never show up after a season is done

**Comment by king8084** [comment]
so any chance of this happening? seriously we need to find a solution lol

99% of private trackers end up useless on Sonarr after the season ends :(

**Comment by kaso17** [comment]
I'm willing to implement a checkbox in the sonarr indexer settings to toggle "Don't search for individual episodes of ended seasons" but would like confirmation that this feature is wanted.

**Comment by king8084** [comment]
YES PLS!!..so when i toggle it on, it will search for the season instead of single eps, once the season ended

its a toggle, so if some people dont want to use it they can opt out, i dont see the downside of it, the trackers are useless once a season is over in the current configuration (the top trackers at least)

**Comment by king8084** [comment]
so are we getting the toggle? :(

**Comment by king8084** [comment]
thank you so much, i can now get season packs to show up on sonarr, i assume you pushed an update to show this

**Comment by kaso17** [comment]
only added this for MTV yes

**Comment by kaso17** [comment]
it always sends two search queries to MTV now, not very elegant...

**Comment by king8084** [comment]
yea need to fix tbh, MTV act crazy now showing all seasons for every time you search a random episode lol

why is it showing every season if im looking for an episode in season 3

**Comment by kaso17** [comment]
MTV has some odd Season searching behavior returning unwanted Seasons packs.
It has been fixed with yesterdays release already.

**Comment by surlias** [comment]
Usenet is a very good long term source for individual episodes, regardless of whether a season has ended or not. Consider complementing Sonarr with NZBHydra which will trawl several free Usenet indexes if you don’t want to spend money on a premium indexer.

**Comment by syluccy** [comment]
Since it's still not working well, could you please enable it for a couple of other indexers?

nCore, BitHUmen, Nebulance, PrivateHD, UHDBits

**Comment by RoloSoze** [comment]
@garfield69 Related to https://github.com/Jackett/Jackett/issues/5147#issuecomment-612307253

**Comment by RoloSoze** [comment]
@garfield69 Should this issue remain open or should it be resolved on Sonarr's end?

**Comment by ngosang** [comment]
I think this is out of the Jackett scope. We allow to search single episodes and season packs. Sonarr is in charge of choose.
