### ISSUE TITLE
[shareisland] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#2332]
Jackett version:  0.8.539.0
Mono version (if not using Windows):  5.4.1.6

-------------------------------
` An error occured while testing this indexer
Found no results while trying to browse this tracker`

Search on this tracker does not work anymore after site redesign.

**Comment by rafuz** [comment]
Some logging when testing from Sonarr


`
Dec 28, 2017 01:35:16 AM | Error | Error on 20171228013516 for Shareisland.txtJackett.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match   at Jackett.Indexers.CardigannIndexer+<TestLogin>d__16.MoveNext () [0x0011b] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:649  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <62f5937022004555807e6c57c33f6684>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <62f5937022004555807e6c57c33f6684>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <62f5937022004555807e6c57c33f6684>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <62f5937022004555807e6c57c33f6684>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <62f5937022004555807e6c57c33f6684>:0    at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__25.MoveNext () [0x0091f] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1131
Dec 28, 2017 01:35:15 AM | Info | CardigannIndexer (shareisland): Relogin required
Dec 28, 2017 01:33:47 AM | Info | Starting web server at http://*:9117/

`

**Comment by kaso17** [comment]
they changed the torrent result view from the table to this new block style.
I'll wait a little until they settle for something final.

**Comment by rafuz** [comment]
I have checked today and they seem to have completed the import of all the torrents in the new tracker.
Also the search results theme seems finalized.

**Comment by kaso17** [comment]
should be fixed in the latest version

**Comment by rafuz** [comment]
I have version 0.8.566.0 but the test and search is still not working.
Logs attached.
[log.20180106.00007.txt](https://github.com/Jackett/Jackett/files/1608635/log.20180106.00007.txt)

**Comment by kaso17** [comment]
Should be fixed via 232819b6bd653a2064a4062336aec8a29951a164 but I can't test because it's offline most of the time...
