### ISSUE TITLE
Error 404 Not found errors

### ISSUE THREAD

**Issue by philborman** [Jackett/Jackett#28]
Getting this in the logs from Jackett
Error downloading strike https://getstrike.net/torrents/api/download/4E7F2F740FB8330E9496797C389964F53C382B3C.torrent

and the client gets a  HTTP Error 404: Not Found

The URL is correct and can be grabbed with wget.

**Comment by flightlevel** [comment]
What version of Jackett?
What OS?
Can you pastebin the log - Instructions here https://github.com/Jackett/Jackett#troubleshooting to enable logging

**Comment by philborman** [comment]
Using Jackett 0.6.9.0 on a RaspberryPi2, debian Jessie ARMHF

http://pastebin.com/tNK0c1SW


I'm implementing Jackett support on LazyLibrarian, correctly getting a 
list of magazines matching a search query. I store the magazine title,  
the provider, the torrent title, torrent url  as follows...

Bookid = natural medicine
tor_prov = http://192.168.2.2:9117/torznab/strike
tor_title = Natural Medicine - May 2015.pdf
tor_url = 
http://192.168.2.2:9117/dl/strike/pkl4u83iz41up73m4zsigqsd4zyie50r/aHR0cHM6Ly9nZXRzdHJpa2UubmV0L3RvcnJlbnRzL2FwaS9kb3dubG9hZC8yRUU1NUUwOUI5OUY4Q0Y5NEM5ODY3OEYyMDcwMjEyQ0Q4NTcxMDRGLnRvcnJlbnQ1/t.torrent

When I try to fetch the torrent file I get the "not found" error as 
shown in pastebin log
If I manually try to wget 
http://192.168.2.2:9117/dl/strike/pkl4u83iz41up73m4zsigqsd4zyie50r/aHR0cHM6Ly9nZXRzdHJpa2UubmV0L3RvcnJlbnRzL2FwaS9kb3dubG9hZC8yRUU1NUUwOUI5OUY4Q0Y5NEM5ODY3OEYyMDcwMjEyQ0Q4NTcxMDRGLnRvcnJlbnQ1/t.torrent
the Jackett log reports

Error downloading strike https://getstrike.net/torrents/api/download/2EE55E09B99F8CF94C98678F2070212CD857104F.torrent


If I manually wget

https://getstrike.net/torrents/api/download/2EE55E09B99F8CF94C98678F2070212CD857104F.torrent


that works, no error.

**Comment by flightlevel** [comment]
Can you report back if this still happens on latest release

**Comment by Inrego** [comment]
Looks like it could be the issue with long url segments that I fixed not so
long ago.

**Comment by flightlevel** [comment]
Hopefully @Inrego There were some good changes in your commit

**Comment by philborman** [comment]
Error is still there on latest release 0.6.26.0, but message has changed to
"No HTTP resource was found that matches the request URI"

New pastebin http://pastebin.com/VTsF4gpP

The URI is returned in the xml result from strike.
The xml also contains a magnet link, and the magnet link works, so I can 
use that instead.

Not sure if this is a problem with strike return values rather than 
Jackett, as strike is the only provider that returns book results. The 
others all seem to ne movies and tv.

Another thought is that the strike URL is https but I am talking to 
Jackett on http, is this relevant?

**Comment by flightlevel** [comment]
The https/http isn't relevant.
Would you have an invite so that we can test.
Any ideas @Inrego ?

**Comment by Inrego** [comment]
As a matter of fact, I can see from the url he posted that the version he's running does not include the changes i made (he has url segments, not query parameters)

**Comment by philborman** [comment]
I am running the version from here...
https://github.com/Jackett/Jackett/releases/download/v0.6.26/Jackett.Binaries.Mono.tgz

**Comment by philborman** [comment]
.solved. jackett xml passes utf-8 nfc. When these were stored they ended up as utf-8 nfd, so although they looked the same, the torrent filename had changed and this generated a "404 - not found" error.
