### ISSUE TITLE
speedcd

### ISSUE THREAD

**Issue by xxcamouflagexx** [Jackett/Jackett#352]
Every time I try to configure speed.cd via Jackett I get configuration failed. After enabling enhanced logging it shows "Exception in test_indexer". This occurred after deleting the entry and re-adding it.

Things I've tried:
- Uninstall and reinstall of Jackett
- Verified latest version
- Change password on speed
- Create json file with speed info manually

Appreciate the help.

**Comment by xxcamouflagexx** [comment]
From log file...

2016-05-27 10:45:23.6296 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__9.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__18.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 263

**Comment by flightlevel** [comment]
Should be fixed in latest release, let us know if it works.

**Comment by xxcamouflagexx** [comment]
Yup, all set. That was impressively fast. Thanks!

**Comment by xxcamouflagexx** [comment]
Unfortunately, this issue is back. It has been occurring for a few weeks now.
