### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www.yggtorrent.to/ using form selector form[action$=

### ISSUE THREAD

**Issue by Ikaer** [Jackett/Jackett#3805]
**Jackett version**:  0.10.178.0
**Mono version** (if not using Windows):  5.8.1.108-11 (syno)

Connection to Yggtorrent does not work anymore. I've try login on website to check, it's working, but not through jackett.

Also not sure how jacket works behind the curtain, but i've executed following code on chrome console when i was not login on yggtorrent: 
![image](https://user-images.githubusercontent.com/7936075/45584839-d3c3b580-b8da-11e8-927c-3b1295a5ebe8.png)

element seem to be there.

log:
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.to/ using form selector form[action$="/user/login"]
  at Jackett.Common.Indexers.CardigannIndexer+<DoLogin>d__16.MoveNext () [0x004b2] in <8651dd0bfab04694a0915d3c8442eda4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Indexers.CardigannIndexer+<ApplyConfiguration>d__24.MoveNext () [0x00079] in <8651dd0bfab04694a0915d3c8442eda4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Server.Controllers.IndexerApiController+<UpdateConfig>d__13.MoveNext () [0x0012d] in <50ff5aad9405478299a7b57213babf47>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <50ff5aad9405478299a7b57213babf47>:0

**Comment by Ikaer** [comment]
Not a duplicate of post #3802: it was closed because of insufficient details without resolution.

**Comment by leo91000** [comment]
Same here !

**Comment by garfield69** [comment]
ygg changed their domain. the next (pre)release should fix this with the inclusion of 8f0ba9cefe319d2223bd1b24de4df6af93d9f8f4.
Alternatively,  you should be able to fix this for yourselves, by accessing the Jackett dashboard, editing the ygg config, and changing the site link to `https://yggtorrent.to/`

**Comment by Karrock** [comment]
Hi @garfield69 the issue isn't fixed yet. I'm in the same situation as @Ikaer he seems to have changed the site link to ```https://yggtorrent.to/``` but it's not working. There is a problem with the form.

**Comment by Ikaer** [comment]
I fixed my problem by directly editing the ygg config file like you suggested. 

But I was not able to do that through the UI.  
With UI, this is what happened:
1/ Edit the line of YggTorrent
2/ Change https://yggtorrent.is/ to https://yggtorrent.to/
3/ Apply
4/ Try to reedit -> error display at bottom, from memory, it was something like "Error contacting server" or something like that.
5/ I had to restart Jacket in syno UI to be able to reopen the configuration of Yggtorrent in the UI after that and it was still on "https://yggtorrent.is/"
Can it be related with something like the file with wrong permission ?

No problem with my account on yggtorrent.
