### ISSUE TITLE
[Waffles] invalid line feed (ASCII 0x000A) in header

### ISSUE THREAD

**Issue by coute** [Jackett/Jackett#4238]
I encounter issues with line break in the title of Waffles releases:
```
System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x000A
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter (System.Char ch) [0x00015] in <dc8a279746124ea5869cb42ff5e7e67b>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderCharacters (System.String headerCharacters) [0x0001b] in <dc8a279746124ea5869cb42ff5e7e67b>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderCharacters (Microsoft.Extensions.Primitives.StringValues& headerValues) [0x00012] in <dc8a279746124ea5869cb42ff5e7e67b>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast (System.String key, Microsoft.Extensions.Primitives.StringValues& value) [0x00000] in <dc8a279746124ea5869cb42ff5e7e67b>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item (System.String key, Microsoft.Extensions.Primitives.StringValues value) [0x00020] in <dc8a279746124ea5869cb42ff5e7e67b>:0 
  at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.SetContentDispositionHeader (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.FileResult result) [0x0004e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.SetHeadersAndLog (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.FileResult result, System.Nullable`1[T] fileLength, System.Boolean enableRangeProcessing, System.Nullable`1[T] lastModified, Microsoft.Net.Http.Headers.EntityTagHeaderValue etag) [0x00023] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Infrastructure.FileContentResultExecutor.ExecuteAsync (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.FileContentResult result) [0x0004b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.FileContentResult.ExecuteResultAsync (Microsoft.AspNetCore.Mvc.ActionContext context) [0x0001e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync (Microsoft.AspNetCore.Mvc.IActionResult result) [0x00049] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync] () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResultExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync] (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x003df] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters () [0x00030] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 
  at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00115] in <560d56f8376d4258a59ad5478913c777>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <fb9fa7d247f445029d871326a8627ee0>:0 
```

**Jackett version**:  0.10.471.0
**Mono version**:  5.16.0.220

-------------------------------

**Comment by kaso17** [comment]
fixed via a466c87d34d655b98891764b73f531c642f1d189

**Comment by coute** [comment]
Hello @kaso17 ,
I still have the issue. Your regex does not match unicode hex control code 0x000A (linefeed) that is an invalid char.
\n will match the line feed.
Thanks.

**Comment by kaso17** [comment]
http://127.0.0.1:9117/jackett/api/v2.0/indexers/waffles/results/torznab/api?apikey=XXX&t=search&cat=&q=Rodrigo+y+Gabriela+-+Re-Foc

returns download links without any 0x0A or 0x0D characters for me. Are you sure you're running the latest version?

**Comment by kaso17** [comment]
Please make sure that the definition file for waffles has been correctly updated (containing the change). Maybe the update wasn't complete due to incorrect permissions of the definition files.

**Comment by coute** [comment]
You're right.
Sorry.
It works.
Thanks.
