### ISSUE TITLE
[rutracker] Cannot add rutracker because Jackett fails to fetch the Captcha image

### ISSUE THREAD

**Issue by azmodai** [Jackett/Jackett#4320]
Issue is in the title. I tried on Firefox and Chrome (latest versions on both)

This is the error message: "An error occured while updating this indexer
Пожалуйста, введите код подтверждения (символы, изображенные на картинке)". Translates to "wrong captcha", basically.

Using Jackett version 0.10.518.0

**Comment by azmodai** [comment]
That doesnt work, nothing works. I didnt fail a login, because I couldnt type the captcha. It asked captcha on the very first try.

**Comment by garfield69** [comment]
@kaso17  can you take a look at this ticket please? thanks

**Comment by kaso17** [comment]
fixed via 6735ad030d0ad2d3ca711b126eb656cc0704a159

**Comment by azmodai** [comment]
> 
> 
> fixed via [6735ad0](https://github.com/Jackett/Jackett/commit/6735ad030d0ad2d3ca711b126eb656cc0704a159)

It still doesnt work. I just updated to 0.10.531.0. Same issue, no captcha at all, just empty space.

**Comment by azmodai** [comment]
Now it updated to 0.10.533.0 and still doesnt work.

**Comment by garfield69** [comment]
@kaso17  shuold the user try deleting the indexer and adding a fresh one, or would this make no difference in this case?

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by azmodai** [comment]
Here are the logs.

[log.txt](https://github.com/Jackett/Jackett/files/2706946/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/2706947/updater.txt)

**Comment by azmodai** [comment]
> 
> 
> it doesn't contain any rutracker configuration attempts. please provide a log including a rutracker config attempt

Here you go, a log file after I attempted to login to rutracker (couldnt log-in obviously, because of a failed captcha)

[log rutracker login attempt.txt](https://github.com/Jackett/Jackett/files/2707661/log.rutracker.login.attempt.txt)

**Comment by britmob** [comment]
Having the same problem. Worked previously but after removing it and trying to re-add it no longer allows me to use rutracker.

**Comment by C0ncat** [comment]
FYI, you can leave the captcha section blank and still login. At first it didn't work for me, but on a second attempt it worked.

**Comment by azmodai** [comment]
> 
> 
> FYI, you can leave the captcha section blank and still login. At first it didn't work for me, but on a second attempt it worked.

This works now.

**Comment by jbd70** [comment]
> > FYI, you can leave the captcha section blank and still login. At first it didn't work for me, but on a second attempt it worked.
> 
> This works now.

Still failing for me on 0.11.256.0

**Comment by dshanks01** [comment]
Still failing on  0.11.534.0

Captcha appeared ONCE immediately after clearing my history/cache/images/login. Login failed that time, and I have not seen the captcha at all since that time (even though I have repeatedly cleared my history).

**Comment by nocniduh** [comment]
I also had a problem of not fetching captcha.

The first attempt returned error wrong username/password. So I made sure I used the right login details and tried again. The second attempt returned bad captcha, and after that I tried another browser. On both browsers I was logged in first, and when I tried to uncheck the option Strip Russian Letters it worked. Then I wanted to see if that had anything to do with successful adding of indexer, so I deleted it and this time it worked even with the option checked.

So I don't know what made it work, I guess you really have to try a couple of times.
