### ISSUE TITLE
[xspeeds] Exception (xspeeds): Sequence contains no elements: Sequence contains no elements (Test)

### ISSUE THREAD

**Issue by brandonscript** [Jackett/Jackett#4458]
Mobile atm so I’m sorry I can’t provide a better bug at this time. More details to follow. 

Was working fine until suddenly it wasn’t. Logs below. 

**Jackett version**:  Version 0.10.611.0
**Mono version** (if not using Windows):  TBD

-------------------------------

```
Jackett.Common.IndexerException: Exception (xspeeds): Sequence contains no elements ---> System.InvalidOperationException: Sequence contains no elements
  at Jackett.Common.Indexers.XSpeeds+<PerformQuery>d__20.MoveNext () [0x003d3] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00091] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ee] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000a3] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by kaso17** [comment]
fixed via 9a417590b61054aa4f4dc1b98efd147f53ad2a05

**Comment by brandonscript** [comment]
Hrm, ok the update fixed Jackett's ability to test, but I'm still getting an error on the Torznab side of things from Sonarr. Any idea whether these are related?

**Message:**
```Unable to connect to indexer: Torznab error detected: Jackett.Common.IndexerException: Exception (xspeeds): Minimum search length is 3 ---> System.Exception: Parse error ---> System.Exception: Minimum search length is 3
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <5b6a7a810ab4440897c6a3446844a720>:0 
  at Jackett.Common.Indexers.XSpeeds+<PerformQuery>d__20.MoveNext () [0x00072] in <5b6a7a810ab4440897c6a3446844a720>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00091] in <5b6a7a810ab4440897c6a3446844a720>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ee] in <5b6a7a810ab4440897c6a3446844a720>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <5b6a7a810ab4440897c6a3446844a720>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Server.Controllers.ResultsController+<Torznab>d__18.MoveNext () [0x00335] in <d4a468c9d9ec448297ad0776fe5acc6a>:0 ```

**Exception:**
```NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (xspeeds): Minimum search length is 3 ---> System.Exception: Parse error ---> System.Exception: Minimum search length is 3
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <5b6a7a810ab4440897c6a3446844a720>:0 
  at Jackett.Common.Indexers.XSpeeds+<PerformQuery>d__20.MoveNext () [0x00072] in <5b6a7a810ab4440897c6a3446844a720>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00091] in <5b6a7a810ab4440897c6a3446844a720>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ee] in <5b6a7a810ab4440897c6a3446844a720>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <5b6a7a810ab4440897c6a3446844a720>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at Jackett.Server.Controllers.ResultsController+<Torznab>d__18.MoveNext () [0x00335] in <d4a468c9d9ec448297ad0776fe5acc6a>:0 
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ca] in <85e2f5295c104ca3a3bcaa59e805585a>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in <85e2f5295c104ca3a3bcaa59e805585a>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in <85e2f5295c104ca3a3bcaa59e805585a>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <85e2f5295c104ca3a3bcaa59e805585a>:0 ```

**Comment by brandonscript** [comment]
@kaso17 do you want me to open a new ticket for this ^ or is this ok?

**Comment by kaso17** [comment]
it's already fixed in the latest version

**Comment by brandonscript** [comment]
Confirmed. Cheers!
