### ISSUE TITLE
Jackett not starting (System.TypeLoadException)

### ISSUE THREAD

**Issue by yigit007** [Jackett/Jackett#4503]
**Jackett version**: v0.10.649.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)
**OS**: Ubuntu 16.04.5 LTS

Installing for the first time, Jackett does not start. Looked similar to #4453, but my Mono is up-to-date. Running as my own user gets me the following:

```
mono --debug Jackett/JackettConsole.exe

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 010000d4 from typeref (expected class 'System.Runtime.InteropServices.RuntimeInformation' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x0000d] in C:\projects\jackett\src\Jackett.Server\Program.cs:51
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <d7beb7c65d8a42b99c2e8878c93a3c3c>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x0007c] in C:\projects\jackett\src\Jackett.Server\Program.cs:47
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 010000d4 from typeref (expected class 'System.Runtime.InteropServices.RuntimeInformation' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x0000d] in C:\projects\jackett\src\Jackett.Server\Program.cs:51
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <d7beb7c65d8a42b99c2e8878c93a3c3c>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x0007c] in C:\projects\jackett\src\Jackett.Server\Program.cs:47
```

**Comment by fuxxociety** [comment]
Having the same issue as OP. 

Jackett 0.10.589 was running well, autoupdated to 0.10.641, now jackett won't start.


The syslog shows a bunch of  entries of "New release found.  Current: v0.10.589 New: v0.10.599", then proceeding with the update, and finally starting 0.10.589 again. Autoupgrade surely wasnt working.

Looks like Autoupgrade finally succeeded.
`Jan 18 18:59:19 lampserver mono[7533]: 01-18 18:59:19 Info New release found.  Current: v0.10.589 New: v0.10.641
Jan 18 18:59:23 lampserver mono[655]: [Info] RssSyncService: Starting RSS Sync
Jan 18 18:59:24 lampserver mono[7533]: 01-18 18:59:24 Info Starting updater: mono /tmp/JackettUpdate-v0.10.641-636834347628761680/Jackett/JackettUpdater.exe --Path "/opt/Jackett" --Type "Console" $
Jan 18 18:59:24 lampserver mono[7533]: 01-18 18:59:24 Info Updater started process id: 12052
Jan 18 18:59:24 lampserver mono[7533]: 01-18 18:59:24 Info Exiting Jackett..
Jan 18 18:59:24 lampserver mono[7533]: Application is shutting down...
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Jackett Updater v0.10.641.0
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Options "--Path" "/opt/Jackett" "--Type" "Console" "--Args" " JackettConsole.exe > /var/log/jackett/mono-daemon.log" "--KillPids" "7533"
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Finding files in: /tmp/JackettUpdate-v0.10.641-636834347628761680/Jackett/
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying anglesharp.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying automapper.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying autofac.extensions.dependencyinjection.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying autofac.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying bencodenet.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying cloudflareutilities.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying commandline.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying csquery.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying datetimeroutines.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying datetimeroutines.pdb
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying icsharpcode.sharpziplib.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackett.common.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackett.common.pdb
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackettconsole.deps.json
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackettconsole.exe
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackettconsole.exe.config
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackettconsole.pdb
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackettupdater.exe
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackettupdater.exe.config
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying jackettupdater.pdb
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying license
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.antiforgery.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.authentication.abstractions.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.authentication.cookies.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.authentication.core.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.authentication.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.authorization.policy.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.authorization.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.connections.abstractions.dll
Jan 18 18:59:25 lampserver systemd[1]: jackett.service: Main process exited, code=killed, status=6/ABRT
Jan 18 18:59:25 lampserver mono[7533]: * Assertion at metadata.c:1159, condition `idx >= 0' not met
Jan 18 18:59:25 lampserver mono[7533]: Stacktrace:
Jan 18 18:59:25 lampserver mono[7533]:   at <unknown> <0xffffffff>
Jan 18 18:59:25 lampserver mono[7533]:   at (wrapper managed-to-native) System.Diagnostics.StackTrace.get_trace (System.Exception,int,bool) [0x00009] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.cors.dll
Jan 18 18:59:25 lampserver mono[7533]:   at System.Diagnostics.StackTrace..ctor (System.Exception,int,bool) [0x0002c] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo..ctor (System.Exception) [0x00039] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture (System.Exception) [0x00019] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Threading.Tasks.TaskExceptionHolder.AddFaultException (object) [0x00028] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Threading.Tasks.TaskExceptionHolder.Add (object,bool) [0x0000d] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Threading.Tasks.Task.AddException (object,bool) [0x00045] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Threading.Tasks.Task.AddException (object) [0x00003] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Threading.Tasks.Task.TrySetException (object) [0x0001e] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]:   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<TResult_REF>.SetException (System.Exception) [0x0002b] in <7b0d87324cab49bf96eac679025e77d1>:0
Jan 18 18:59:25 lampserver mono[7533]: * Assertion at metadata.c:1159, condition `idx >= 0' not met
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.cryptography.internal.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.dataprotection.abstractions.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.dataprotection.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.diagnostics.abstractions.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.diagnostics.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.hostfiltering.dll
Jan 18 18:59:25 lampserver mono[7533]: 01-18 18:59:25 Info Copying microsoft.aspnetcore.hosting.abstractions.dll
Jan 18 18:59:25 lampserver systemd[1]: jackett.service: Unit entered failed state.
Jan 18 18:59:25 lampserver systemd[1]: jackett.service: Failed with result 'signal'.
`

My system details:
ESXi Virtual Machine Version 8. ESXi is presenting 2 dual-core CPUs to the VM. 

> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 44
> model name      : Intel(R) Xeon(R) CPU           L5630  @ 2.13GHz
> 

Debian 9.5 (x64)
mono version: 5.18.0.225 (tarball Fri Dec 21 19:41:01 UTC 2018)

**Comment by mscaff** [comment]
Having the exact same problem myself, seeing the same logs upon running 'mono --debug JackettConsole.exe'

ESXi VM - 2 Cores, 2GB RAM
Debian 9.6
Latest Mono-devel

Tried latest release v0.10.641 as well as latest pre-release

**Comment by yigit007** [comment]
Release 0.10.641 has the same error for me. My CPU is Intel Atom N2800. 
Pasting the new version’s log as well since there might be very small differences I may have not noticed. 
```
Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 010000d4 from typeref (expected class 'System.Runtime.InteropServices.RuntimeInformation' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x0000d] in C:\projects\jackett\src\Jackett.Server\Program.cs:51 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <d7beb7c65d8a42b99c2e8878c93a3c3c>:0 
  at Jackett.Server.Program.Main (System.String[] args) [0x0007c] in C:\projects\jackett\src\Jackett.Server\Program.cs:47 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 010000d4 from typeref (expected class 'System.Runtime.InteropServices.RuntimeInformation' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x0000d] in C:\projects\jackett\src\Jackett.Server\Program.cs:51 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <d7beb7c65d8a42b99c2e8878c93a3c3c>:0 
  at Jackett.Server.Program.Main (System.String[] args) [0x0007c] in C:\projects\jackett\src\Jackett.Server\Program.cs:47
```

**Comment by Fyb3roptik** [comment]
Happening for me on Debian 9 fresh install

**Comment by Fyb3roptik** [comment]
639 has the same issue as well for me

**Comment by Nico769** [comment]
**Jackett version:** v0.10.641.0
**Mono version:** Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)
**OS:** OSMC 2018.12-1 running on a Raspberry Pi 2 Model B (ARM Cortex-A7)

Installing `mono-complete` solved the issue for me

**Comment by yigit007** [comment]
Confirming  problem is solved with the install of mono-complete. Closing the issue as the problem is probably a missing mono component

**Comment by Fyb3roptik** [comment]
This should be documented somewhere in the docu. Please dont just close this. DOCUMENT IT

**Comment by Fyb3roptik** [comment]
Also this did NOT solve it for me. Please dont close a ticket until verification that this works!

**Comment by fuxxociety** [comment]
> **Jackett version:** v0.10.641.0
> **Mono version:** Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)
> **OS:** OSMC 2018.12-1 running on a Raspberry Pi 2 Model B (ARM Cortex-A7)
> 
> Installing `mono-complete` package solved the issue for me

Which version of mono-complete are you running? The debian repos may not be as up-to-date as OSMC.

Simply installing mono-complete (mono-complete/stable-jessie 5.18.0.225-0xamarin1+debian8b1) on my Debian 9.5 build did not solve the issue.

**Comment by flightlevel** [comment]
@fuxxociety 
Can you try clean install of Jackett binaries (either by deleting all binaries and downloading latest release or downloading latest release and trying from a different folder)
I suspect one of the files is missing/corrupted

@Fyb3roptik 
How would documenting it help? The documentation (readme) mentions the minimum Mono multiple times but your still running a version of Mono from 3 years ago https://github.com/Jackett/Jackett/issues/4524#issue-402374446

99% of Jackett users aren't using mono-complete and shouldn't need. Have found it solves issues for a small number of users, suspect related to OS/CPU. The .NET Core version of Jackett will hopefully solve a lot of these issues

**Comment by Nico769** [comment]
> @Nico769 Which version of mono-complete are you running? The debian repos may not be as up-to-date as OSMC.

```
apt list -a mono-complete
Listing... Done
mono-complete/stable-stretch,now 5.18.0.240-0xamarin1+debian9b1 armhf [installed]
```

**Comment by Fyb3roptik** [comment]
@flightlevel Debian does not have as up to date repos as Ubuntu or other Distros strictly because they want stability. So unless the documentation specifies a version, we are going to assume whatever is in the Debian distro will work.

**Comment by sp0tz** [comment]
> **Jackett version:** v0.10.641.0
> **Mono version:** Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)
> **OS:** OSMC 2018.12-1 running on a Raspberry Pi 2 Model B (ARM Cortex-A7)
> 
> Installing `mono-complete` package solved the issue for me

This worked for me too.

**Comment by Fyb3roptik** [comment]
Can we get the README updated to show which version of Mono to use?
