### ISSUE TITLE
Bug: Torrent download links are wrong in Jackett and in Torznab

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4731]
Torrent download links are wrong in Jackett and in Torznab.

Setup:
1. I start Jackett in a server with IP 192.168.0.190 Port 9117
2. I have configured a Reverse Proxy so http://mydomain.com/* goes to http:192.168.0.190:9117/*
=> https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy
3. In a remote computer I can access the Jackett UI with and without the reserve proxy
4. In the following cases I'm always searching "harry potter" in Monova indexer.

**Manual search in the Web UI:**
Working case
WebUI http://192.168.0.190:9117/jackett/...  => Download link http://192.168.0.190:9117/jackett/dl/monova...
Error case, in this case I can't download because Jackett is running in a remote machine
WebUI http://mydomain.com/jackett/...  => Download link http:// **127.0.0.1:9117** /jackett/dl/monova...

**Torznab API:**
Error case 1, I can't download and the port is weird, I suppose you are trying to guess something but there are several NATs between my machines...
Torznab http://192.168.0.190:9117/api/...  => Download link http:// **localhost:8081** /jackett/dl/monova...
Error case 2, in this case I can't download because Jackett is running in a remote machine
WebUI http://mydomain.com/jackett/...  => Download link http:// **127.0.0.1:9117** /jackett/dl/monova...

**Fix:**
IMHO there are 2 ways to fix that:
1. Autodetect the request URL and use the same in the response
2. Let the user configure the Reverse Proxy in configuration, the same as the "Base Path Override"

We did an ugly hack in qBittorrent to fix that... https://github.com/qbittorrent/search-plugins/blob/master/nova3/engines/jackett.py#L140

**Jackett version**:  latest

**Comment by ngosang** [comment]
Related to #4607

**Comment by McGriddle** [comment]
A workaround that's worked for me is to use the sub_filter directive to re-write the responses. I run the server on 4443. The UI links all have 443 as the port so rewrite that. The torznab links don't have a port at all so I rewrite those. All working for me.
```
location ~ /jackett/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
    proxy_set_header Accept-Encoding "";
    sub_filter_types *;
    sub_filter ":443/" ":4443/"; # for UI d/l link
    sub_filter "https://172.26.4.1/" "https://172.26.4.1:4443/"; # for torznab link
    sub_filter_once off;
}
```

**Comment by kaso17** [comment]
Just setting the X-Forwarded-* headers correctly should fix it too.
See the README: https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

**Comment by ngosang** [comment]
> Just setting the X-Forwarded-* headers correctly should fix it too.
> See the README: https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

@kaso17 Thank you for the replay. I changed the Nginx according to the readme and it fixes the web ui, but the torznab api is still wrong. Please, don't underestimate the importance of this issue.

**Manual search in the Web UI:**
WebUI http://192.168.0.190:9117/jackett/... => **WORKING**
WebUI http://mydomain.com/jackett/... => **WORKING**

**Torznab API:**
Torznab http://192.168.0.190:9117/api/... => Download link http:// **localhost:8081** /jackett/dl/monova...
Torznab http://mydomain.com/jackett/api/... => Download link http:// **localhost:8081** /jackett/dl/monova...

**Comment by flightlevel** [comment]
@ngosang You're not the first person to use Jackett with nginx. Its working perfectly here (using LetsEncrypt with nginx in a docker container) and I can see my domain included in the torznab api response content. 
Post your nginx configuration and someone may be able to help

**Comment by ngosang** [comment]
@flightlevel You are right, my fault. I have a complex installation and my API Gateway was messing up the headers. All is working fine.
