### ISSUE TITLE
Jackett Not Starting Properly with System

### ISSUE THREAD

**Issue by trevorgentry** [Jackett/Jackett#4820]
Jackett is not starting with Windows properly. I am running Windows 10 Pro, fully updated as of today, and Jackett 0.10.861.0. This error only occurs after the application updates itself. I have Jackett installed as a Windows service, and when I first install the newest version of Jackett manually, it starts with Windows fine, but once it updates itself, it stops starting properly and the webpage won't load. The only way to fix it is to run Jackett again, and then stop the background service and start it again. Then the webpage loads fine. This issue has been occurring over the last five or so updates I have received over the course of a few weeks at least, and every time I install manually, it works fine, but then it breaks itself after updating. I will be updating Jackett manually today to the most current version (0.10.887 as of now) and hope to see this issue resolved at some point.

Edit: Jackett has been many versions behind apparently due to it not starting with my system correctly and therefor being unable to launch an update.

Edit 2: I have updated Jacket to the most current version (0.10.887) and it starts with my system fine. I will update this when the next update is released to let you know if the program breaks.

**Comment by garfield69** [comment]
if it happens again find the updater.txt file in C:\ProgramData\Jackett and drag/drop it here so we can have a look.
Also, visit your windows event logs (application, System, Security) and look for errors relating to starting the jackett service. It is most likely a lack of admin authority.

**Comment by garfield69** [comment]
there has been an issue with auto-updates beginning with 0.10.869, but should be resolved from 0.10.903 onward. see #4827 for more details.

**Comment by trevorgentry** [comment]
It did try to update itself, and failed to launch properly with Windows as a result. I will manually install the newest current version (0.10.906) and let you know if the problem persists.

**Comment by trevorgentry** [comment]
The problem persists after the program self-updated to 0.10.911.0.

**Comment by garfield69** [comment]
then provide the log.txt and updater.txt as requested previously so we can take a look if there is a clue.

**Comment by trevorgentry** [comment]
[updater.txt](https://github.com/Jackett/Jackett/files/2947737/updater.txt)
[log.txt](https://github.com/Jackett/Jackett/files/2947738/log.txt)

**Comment by garfield69** [comment]
the files you provided show that the auto-update is working as expected.
there is no problem :-)
the issue here is simply one of perception. 
you are expecting the jackett dashboard on your browser to automatically refresh after the update so that the version number at the bottom of the page reflects the update, but that is not possible to do automatically.
you just need to press CTRL F5 and refresh the browser yourself a little while after the update is done, or start a fresh tab to open a new Jackett dashboard.
Then you will see that the version has been updated ;-).

**Comment by trevorgentry** [comment]
The issue is that, upon restarting my computer, Jackett does not start as it should. After restarting my PC, Sonarr, Radarr, and Lidarr are all immediately accessible, but Jackett says the page could not be found. The only way to remedy this issue is to manually run Jackett, and stop the background sefvice, then start the background service. Only then does the Jackett dashboard become accessible. This problem is only introduced after Jackett has preformed an automatic update, and the issue is not introduced in manual/first installs of the program. Upon starting my PC, I can see that there is a Jackett service running, but I am unable to access the Jackett dashboard, and Sonarr, Lidarr, and Radarr are all unable to connect to Jackett as a result.

**Comment by garfield69** [comment]
ok then, this is beyond my skills to diagnose. I'll pass it on to the more experienced devs.
@kaso17  @flightlevel  your assistance with this ticket requested. Thanks.

**Comment by trevorgentry** [comment]
Thank you for your attempt, I appreciate you taking your time to help with this issue.

**Comment by garfield69** [comment]
found this in the log provided, just after the update completed and restart is attempted:
```
2019-03-08 16:21:27.3182 Info Starting Jackett v0.10.911.0 
2019-03-08 16:21:28.6777 Error Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ServerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IServerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) ---> System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Jackett.Common.Utils.Clients.HttpWebClient.InitProxy(ServerConfig serverConfig)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ServerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IServerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) ---> System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Jackett.Common.Utils.Clients.HttpWebClient.InitProxy(ServerConfig serverConfig)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
``` 
buggered if I know what to do about it though :-(

**Comment by mobamoba** [comment]
I'm getting the exact same error with no Jackett service after most recent update.

**Comment by flightlevel** [comment]
@trevorgentry 
If you have a proxy setup in Jackett, can you remove, restart the PC and then see if the same thing happens.

Then try changing the service type from Auto to Auto (delayed start) and restart PC

Are you using any VPNs? Strange DNS setup?

**Comment by trevorgentry** [comment]
I am running a SOCK5 proxy on Jackett, yes. I'm running the same proxy on Sonarr, Lidarr, and Radarr, and it doesn't seem to be an issue, but all software is different I guess. I restarted my PC and noticed that Jackett is accessible, but I haven't disabled my proxy yet. Will do more restarts to test.

**Comment by trevorgentry** [comment]
Further restarts yielded no results, but disabling the proxy seems to have solved the issue on my end. I can have no proxy on Jackett, it's not that big of a deal to me if it's the only solution, but I'd like to run a proxy if I can. Just for privacy's sake.

**Comment by garfield69** [comment]
>Where would I find the option to switch Jackett to Auto (delayed start)? I'd assume this is in Task Scheduler, but I don't see it.

its a service option, so from your *control panel > administrative tools > Services* page, find Jacket, click on *Properties* and change the *startup type* drop box from *automatic* to **automatic delayed start**

**Comment by trevorgentry** [comment]
I changed it to Delayed Start and it still works without a proxy, but it takes a full couple minutes to start.

**Comment by flightlevel** [comment]
Delayed start as the name implies will delay it by a little bit, but the gives the PC time to load up necessary network connection

**Comment by WiliTest** [comment]
On Windows 10 I set the service to "demand start". I guess the service should run when it's required but it doesn't : when I search on qbitorrent (the search needs the service), it doesn't turn on the jacket service  (I need to turn it ON manually). Is it an issue with qbitorrent or jacket?

**Comment by tifo71** [comment]
I had the same problem so I found the solution. You must not install the Jackett service so uncheck the installation of the service. Then right click on the jackett icon and click on Auto start on boot.
