### ISSUE TITLE
[spacetorrent] Exception (spacetorrent): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Jackett/Jackett#4982]
Hi

Here is the error I get now when testing the connection with Spacetorrent : 

Exception (spacetorrent): Specified argument was out of the range of valid values. Parameter name: Unknown operator: : Specified argument was out of the range of valid values. Parameter name: Unknown operator: 

No idea what it could be !

**Comment by garfield69** [comment]
when I last saw this error about a week ago it turned out to be a change to the CloudFlare DDoS protection page which was tripping up the CloudflareUtilities library that Jackett uses to attempt to solve these challenges.
However, before the owner of the library could implement an update, Cloudflare rolled back their changes.
It seems that page has been implemented again, so now we wait to see what happens next.
I've updated https://github.com/elcattivo/CloudFlareUtilities/issues/44

**Comment by arqcan** [comment]
Do you know if there has been any progress on this?

**Comment by garfield69** [comment]
no progress. waiting on a volunteer to fix.

**Comment by adambirds** [comment]
Same issue for me with worldwidetorrents too.

**Comment by psychogun** [comment]
Same here. Googled around, found this - could this be helpful? https://github.com/Anorov/cloudflare-scrape/pull/206

**Comment by psychogun** [comment]
Nothing new here? :(

**Comment by garfield69** [comment]
@flightlevel   looks like @kaso17  is awol. is there any chance you can contribute to https://github.com/elcattivo/CloudFlareUtilities/issues/44 ?
its not my cup of tea.

**Comment by psychogun** [comment]
@garfield69 looks like @flightlevel is also awol :(

Jackett variant; Mono - v0.11.295

**Comment by garfield69** [comment]
we have progress of sorts, a pull request has been submitted https://github.com/elcattivo/CloudFlareUtilities/pull/49 were now waiting on final acceptance/modifications and who knows, we may get something, sometime ;-)

**Comment by psychogun** [comment]
Thank you for the quick reply! @garfield69 
I'll be waiting :)

**Comment by psychogun** [comment]
As of v0.11.348, this issue now seems to have been solved. Thanks, @garfield69 :)

**Comment by Primeey** [comment]
Really? Because I''m on 0.11.348.0 and I still have the issue but instead on spacetorrent it's for 1337x

**Comment by psychogun** [comment]
Ah, sorry - for me the issue was for WWT - that is now in ordnung. 
1337x works for me, 'Test successfull'
I do not have spacetorrents.

**Comment by psychogun** [comment]
@Primeey - now it does not work again (WWT). Hmm.

**Comment by garfield69** [comment]
we are still waiting on the 3rd party cloudflareuntilities to be updated to handle the new cloudflare challenges.
if at any time jackett works with a site before that library is updated, it will most likely be because the site dropped the cloudflare challenge, or switched to a challenge that the cloudflareutilities library can already solve.

**Comment by psychogun** [comment]
@garfield69 OK!

**Comment by flydahli** [comment]
any news same problem

**Comment by arsenicks** [comment]
@garfield69 Could you point us to the issue/bug report that has been opened for CloudFlareUtilities so we can monitor progress or try to help ?  Thanks!

**Comment by garfield69** [comment]
elcattivo/CloudFlareUtilities#44

**Comment by crashseb** [comment]
same problem for me with torrent9

and new url for the clone/mirror : https://wwv.torrent9.lol/

**Comment by hergonoway** [comment]
same problem for me with Torrent9, Torrent9 Clone, capsien, GkTorrent

**Comment by Oz246** [comment]
Is it possible to have news?

**Comment by garfield69** [comment]
the news is that there is no news.
we are waiting on elcattivo/CloudFlareUtilities#44 to be resolved by owner of the utility.

**Comment by arqcan** [comment]
I dont know much about these things but are there no other utilities or
options that you could incorporate?

**Comment by garfield69** [comment]
probably, but since I'm not a c# developer its not in my box.
All the c# devs seems to be awol atm, both on jackett and elcattivo.
I'm left keeping the lights on ;-)

**Comment by arsenicks** [comment]
Hi guy's just posting an update on this issue, does anyone has solved the problem or found a workaround ?

On the issue @garfield69 pointed out, some dev has posted an update few days ago. I think he fixed the problem but it seems to be in another utils, not in cloudfaireutilities tho..

https://github.com/elcattivo/CloudFlareUtilities/issues/44#issuecomment-513174609

**Comment by psychogun** [comment]
My workaround was to use another tracker :o

**Comment by rrrevin** [comment]
As more and more sites start using CloudFlare, this is going to become an ever increasing issue. Indeed, we are now seeing this on more sites.

I looking though the treads in {[CloudFlareUtilities Issue #44](https://github.com/elcattivo/CloudFlareUtilities/issues/44)}. It seems near the end {[RyuzakiH comment Jul 19, 2019](https://github.com/elcattivo/CloudFlareUtilities/issues/44#issuecomment-513174609)}, someone has a possible fix in their code, and has made it available. I'm not Mono savy, so I can't fix this, but I hope I can point the devs here in the right direction. Is it possible to look at https://github.com/RyuzakiH/CloudflareSolverRe as a possible replacement/partial enhancement for  https://github.com/elcattivo/CloudFlareUtilities

Thoughts?

**Comment by garfield69** [comment]
solved with Jackett 0.11.635
