### ISSUE TITLE
iptorrents can't sign in "configuration failed"

### ISSUE THREAD

**Issue by JohnnyT009** [Jackett/Jackett#591]
This is my first time trying Jackett and I tried on my unraid setup with docker and with a windows installation both give me an error and will not let me add iptorrents. I have a working login and password as I tested them.  I noticed in the last few days searching iptorrents from sickrage has also stopped working was there a change that broke both programs?

![image](https://cloud.githubusercontent.com/assets/17319469/19826025/59086012-9d47-11e6-91da-6341ef4f578c.png)

**Comment by kingwoftam** [comment]
I've got the same issue, thought it was me but looks like it's a wider problem.

Running Jackett Version 0.7.425.0 and an attempt to configure iptorrents, results in the following log entry:
Rejected a request to IPTorrents which is unconfigured.

**Comment by kaso17** [comment]
This was fixed with #587, release is still pending

**Comment by JohnnyT009** [comment]
Still does not appear to be working. Sickrage is working now but it made me add cookie uid and password to login.

**Comment by kaso17** [comment]
please provide a full log (with -t option)

**Comment by JohnnyT009** [comment]
Sorry, thought I updated this. It's working now with the latest update. Thank you.
