### ISSUE TITLE
 Error: This operation is not supported for a relative URI.

### ISSUE THREAD

**Issue by sagivstern** [Jackett/Jackett#5935]
Hi, 
First of all I want to say thank you for this amazing work, I have been using jackett for a while now and it suits my needs perfectly.

I'm having difficulties trying to get this to work after changing VPS.
My version of jackett is 0.11.659.0 installed through quickbox.io.
My apache configuration uses reverse proxy.

`ProxyPreserveHost On`
`RequestHeader set X-Forwarded-Proto "https"`
`ProxyPass /jackett http://127.0.0.1:9117/` 

After settings up the indexer and the manual blackhole directory I attempt to download to BH directory so it will be picked up by deluge.
The error I get while BH'ing is:

` Error: This operation is not supported for a relative URI.`

Thank you.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

**Comment by sagivstern** [comment]
> https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

Thanks for the quick reply tho its still the same after adding that to apache2.conf

**Comment by sagivstern** [comment]
Are there any details I can provide to help with this problem?

**Comment by garfield69** [comment]
I don't know anything about using jackett with proxy or how the blackhole works, which is why I assigned the ticket to the resident c# experts.
But I suppose if you provided the **full enhanced log** file there may be something useful in there.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here.

Thanks.

**Comment by sagivstern** [comment]
https://pastebin.com/a88Q5JSY

Hope this helps

**Comment by sagivstern** [comment]
I've been messing around with my VPS installing different versions of ubuntu and different deployments of jackett (swizzin, quickbox, bytesized) without any luck (nginx or apache reverse proxy and without)
I did forget to mention that the tracker I'm experiencing problems with is TorrentLeech
I dont have any other trackers so cant test anything else.
Any other possible solutions off the top of the head are welcome.
Thank you!

**Comment by sagivstern** [comment]
*Update*
A friend took a swing at trying to work this out and changed this commit back to original and deployed on my server

https://github.com/Jackett/Jackett/commit/f05e1321b5877f7946fb57af12828715d6ef2ca1#diff-b43a161545ad5fe4f56581009cb91259

it seems to work fine now.
I think torrentleech changed something recently causing an issue but honestly I have no clue.

**Comment by ghsi10** [comment]
I fixed it by revert commit #5901 

There was a problem in **torrentleech** and after the revert it works perfectly.

**Comment by ngosang** [comment]
@sagivstern  Is this solved?

**Comment by sagivstern** [comment]
@ngosang It seems like its still the same on the most recent update so I guess its not fixed.
I just use version v0.11.635 which doesnt have this "fix"

**Comment by ngosang** [comment]
I recommend you to update Jackett anyway.

**Comment by sagivstern** [comment]
Im using jackett specifically for blackhole usage and it seems broken on the new versions.
Updating is the same as uninstalling for me.
Thanks for the reply non the less.

**Comment by grozan** [comment]
Hi,

same problem here with jackett 0.12.1623.0
the issue is tracker-specific, apparently.
for me the blackhole works for ipt, but doesn't for xthor
"download locally" works for both.

relevant log
```
01-31 10:00:21 Error Error downloading to blackhole xthor 123456&torrent_pass=XXXXXXXXXXXXXXXXXXXXXXXXXX System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Scheme()
   at Jackett.Server.Controllers.BlackholeController.Blackhole(String indexerID, String path, String jackett_apikey, String file) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/BlackholeController.cs:line 56
```

**Comment by grozan** [comment]
Hi,

I tried to do some debugging, and I *think* I might have found something.

The path which gets passed to the BlackholeController, and which gets decoded at
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Server/Controllers/BlackholeController.cs#L51
is indeed wrong for xthor results.
The value which is passed is like `12345&torrent_pass=xxxxxxxxxxxxxxxxxx`, instead of the expected `https://xthor.tk/download.php?torrent=12345&torrent_pass=xxxxxxxxxxxxxxxxxx`

The value retrieved from the xthor API is correct.

The special thing about that tracker is that it has a `downloadBase` defined
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Xthor.cs#L54

Very few trackers have

```
$ grep -wl "downloadBase:" -R *
Jackett/src/Jackett.Common/Indexers/Hebits.cs
Jackett/src/Jackett.Common/Indexers/TorrentLeech.cs
Jackett/src/Jackett.Common/Indexers/Xthor.cs
Jackett/src/Jackett.Common/Indexers/RevolutionTT.cs
Jackett/src/Jackett.Common/Indexers/Abnormal.cs
```

The `release.Link`, which is correctly loaded at first in the respective `PerformQuery` function, gets screwed up later on when the `CleanLinks` function is called at
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/BaseIndexer.cs#L804

The `downloadBase` gets removed, and the valid link becomes `12345&torrent_pass=xxxxxxxxxxxxxxxxxx`

New to Jackett, therefore I don't know what this `downloadBase` is for, neither do I know why the `CleanLinks` function exists at all, but it looks like it's the root cause of this particular issue.

**Comment by ngosang** [comment]
@grozan thank you for pointing in the right direction.
This PR fixes the issue for all trackers =>  #7057

**Comment by garfield69** [comment]
jackett 0.12.1669
