### ISSUE TITLE
Previous proxy settings still used when all fields are empty

### ISSUE THREAD

**Issue by MrDemocracy** [Jackett/Jackett#6215]
If I change my proxy settings to any IP/port, and then try to disable proxy settings by clearing the fields. The previous IP/port are still being used. `ServerConfig.json` doesn't have the previous proxy settings in it anymore. I have to restart the Jackett background service in order to disable the proxy.

-Jackett Version 0.12.836.0
-Windows 10

**Comment by garfield69** [comment]
that is correct. changes to the jackett dashboard do not take effect until you click on the "apply server settings" button

**Comment by MrDemocracy** [comment]
I'm clicking the "apply server settings" button after I add the IP/port and after I remove it. I can see the settings being changed in `ServerConfig.json`. But when I remove the IP/port and click "apply server settings", the previous settings are still being used.

**Comment by garfield69** [comment]
ok thanks.
I don't know what is going on there then.
assigning to a c# dev,

**Comment by garfield69** [comment]
should be fixed, beginning with jackett pre-release 0.12.845

**Comment by MrDemocracy** [comment]
The issue isn't completely fixed. It looks like it fixed socks4/5 but not http.
