### ISSUE TITLE
GFTracker : Configuration failed: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#662]
Using Jackett on Windows 10:

Configuration failed: Found no results while trying to browse this tracker

Error	
Exception in Configure
Nov 08, 2016 04:52:34 AM	Info	
Found 0 releases from GFTracker
Nov 08, 2016 04:52:34 AM	Error	
Error on 20161108045234 for GFTracker.txtSystem.Exception: TimeAgo parsing failed, unknown unit: -
   at Jackett.Utils.DateTimeUtil.FromTimeAgo(String str) in C:\projects\jackett\src\Jackett\Utils\DateTimeUtil.cs:line 71
   at Jackett.Indexers.GFTracker.<PerformQuery>d__12.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\GFTracker.cs:line 186

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
		
		<html xmlns='http://www.w3.org/1999/xhtml'>
		<head>

			<meta name='generator' content='TBDev.net' />
			<meta http-equiv='Content-Language' content='en-us' />
			<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
			<meta name='MSSmartTagsPreventParsing' content='TRUE' />
			
			<title>GFT 2016 :: Search results for </title>
<link rel='alternate' type='application/rss+xml' title='Latest Torrents' href='https://www.thegft.org/rss.php?passkey=21c3ffd7fc352711a8aa908a1deff6d1' />
			<link rel='stylesheet' href='/templates/1/1.css' type='text/css' />
			<link rel='shortcut icon' href='pic/tb.ico' />
			<link href="/scripts/jqgft.css" rel="stylesheet" type="text/css"/>
			<script type="text/javascript" src="/scripts/jquery.js"></script> 
			<script type="text/javascript" src="/scripts/jquery-ui.js"></script>
			<script type="text/javascript" src="/scripts/gft.js"></script>
			<script type="text/javascript" src="/scripts/ncode_imageresizer.js"></script>
			<script type="text/javascript">
			
			</script>
			
		</head>
    
    <body>
	<div class='page'>
	  <a href='donate.php' alt='Donate' class='firefox'></a>
	  
      <table id='header' align='center' cellspacing='0' cellpadding='0'>
      <tr>

      <td class='clear'>
      <div id='logostrip'>
	  <div id='logo-text'>
			<a href='/index.php'>GFTracker</a>
		</div>
		
      
	  
	 
	<div class='submenu'>
		<ul>

      
      <li><a href='usercp.php'>User CP&nbsp;</a></li>
      <li><a href='mircstats.php'>IRC Stats&nbsp;</a></li>
      <li><a href='users.php'>Users&nbsp;</a></li>
      <li><a href='friends.php'>Friends&nbsp;</a></li>      
      <li><a href='topten.php'>Top 10&nbsp;</a></li>
	  	<li><a href='blackjack.php'>Blackjack&nbsp;</a></li>
	  	<li><a href='viewoffers.php'>Offers&nbsp;</a></li>
	  	<li><a href='links.php'>&nbsp;Links&nbsp;</a></li>

      
      
      </ul>
      </div> <div class='nava'>
			<ul>
     			<li><a href='index.php'>&nbsp;Home&nbsp;</a></li>
     			<li><a href='browse.php?view=0'>&nbsp;Browse&nbsp;</a></li>
     			<li><a href='browse.php?view=1'>&nbsp;Browse/Gems&nbsp;</a></li>
     			<li><a href='tv.php'>TV&nbsp;</a></li>
     			<li><a href='movies_index.php'>Movies&nbsp;</a></li>
     			<li><a href='viewrequests.php'>Requests&nbsp;</a></li>     			
     			<li><a href='upload.php'>&nbsp;Upload&nbsp;</a></li>
				<li><a href='myBB/index.php'>&nbsp;Forums&nbsp;</a></li>
     			<li><a href='irc.php'>&nbsp;Chat&nbsp;</a></li>
                
				<li><a href='rules.php'>&nbsp;Rules&nbsp;</a></li>
				<li><a href='faq.php'>&nbsp;Faq&nbsp;</a></li>
				<li><a href='staff.php'>&nbsp;Staff&nbsp;</a></li> 
     			<li><a href='donate.php'>&nbsp;Donate&nbsp;</a></li>
     			
     			
     			      
			</ul>				
      </div><div class='clear'></div>	
							<div class='navb'>
			      	<table width='100%' cellspacing='0' cellpadding='0' style='background: transparent' align='center'>
				      	<tr>
				      		<td class='clear' align='center'>
				      			<br />
				      			<table>
				      				<tr>
				      					<td>
													<a href='https://www.thegft.org/donate.php'><img border='0' src='/pic/makedonation.gif' alt='Donate' title='Donate'  /></a>&nbsp;
												</td>					      				
				      					<td>
					<table width='650' style='height: 15;' border='0' cellspacing='0' align='center'>
    				<tr>
    					<td bgcolor='#0C571E' align='center' valign='middle' width='73%'><font color='white'>73.0%</font></td>
    					<td bgcolor='#940C23' align='center' valign='middle'></td>
    				</tr>
    			</table>Daily donations are low, <b>please</b> donate whatever you can.<br /><center>The monthly site cost per active user is &#8364;0.04, our next bill on November 19th (<a href='site_costs.php'>Site Costs</a>)<br /></td>
				      					<td>
													<a href='https://www.thegft.org/donate.php'><img border='0' src='/pic/makedonation.gif' alt='Donate' title='Donate'  /></a>&nbsp;
												</td>																									
											</tr>
										</table>
				      		</td>
				      	</tr>
			      </table>
			      <br />
			      </div><tr><td colspan='2' style='padding: 2px;'><div id='statusbar'><div style='float:left;'>Welcome back, <a href='userdetails.php?id=37377'>seanvree</a>&nbsp&nbsp&nbsp;&nbsp;[<a href='logout.php'>Logout</a>]<br />Uploaded:<span style='color:#f75e11;'>&nbsp;0.00 kB</span>&nbsp;&nbsp;Bonus Points:&nbsp;<a href='mybonus.php' title='Bonus Points'>0.0</a>&nbsp;&nbsp;Active Torrents:&nbsp;<img alt='Seeding' title='Seeding' src='pic/arrow-up.png' />&nbsp;0&nbsp;&nbsp;<img alt='Leeching' title='Leeching' src='pic/arrow-down.png' />&nbsp;0&nbsp;<font color=red><b>!</b></font>&nbsp;<a href=notsafedelete.php?id=37377>0</a>&nbsp;-&nbsp;Invites:&nbsp;<a href='https://www.thegft.org/invite.php'>0</a></div><div><p style='text-align:right;'>Tue, 8 Nov 2016, 12:52:35 GMT<br /><a href='messages.php'>0&nbsp;New Messages</a></p></div></div></td></tr></div>
	
	
     </td>
      </tr></table>

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll fix it.

**Comment by armani316** [comment]
Yeah I can confirm that I'm having the same problem here!

**Comment by seanvree** [comment]
Yup, still an issue:

pastebin.com/embed_js/uS6hHaai

**Comment by kaso17** [comment]
looks like they made some larger design changes.
It shouldn't be hard to fix if anyone got an invite to spare.

**Comment by seanvree** [comment]
@kaso17 ...roger, I don't have an invite right now, but I'll work on it!

**Comment by armani316** [comment]
@seanvree Is it working for you? I'm still having the same issue.

**Comment by seanvree** [comment]
Nope, I messaged the staff asking for an invite and they came back with jerkface response. So, whatevs

**Comment by armani316** [comment]
Damn, that's cold! @seanvree

**Comment by armani316** [comment]
@kaso17 Invite sent

**Comment by seanvree** [comment]
YAS! thank you @armani316

**Comment by kaso17** [comment]
fixed with eed8cb70a3ef1b4d7065374c3b0d705e4af611d2

**Comment by seanvree** [comment]
YAS! Thanks kaso!!!!!!

**Comment by nsiti** [comment]
I still get the same error
Configuration failed: Found no results while trying to browse this tracker
Did this break again?

**Comment by armani316** [comment]
@nsiti Working fine for me. Have you tried deleting the tracker and adding it again? If that doesn't work, please post the enhanced log here.

**Comment by nsiti** [comment]
Hi, when trying to add indexer GFT, I get the error. It does not get added, so not sure I understand how I can delete the tracker.

**Comment by armani316** [comment]
@nsiti Please post the enhanced log.

**Comment by nsiti** [comment]
Error on 20170128220503 for GFTracker.txtSystem.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at Jackett.Indexers.GFTracker.<PerformQuery>d__12.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\GFTracker.cs:line 202

**Comment by kaso17** [comment]
Set "Torrents in relative time" to no in the user CP/Tracker settings.
I'll add support for relative time.

**Comment by kaso17** [comment]
fixed with e5bb25abf5a469aa437614134c685699b6995aed

**Comment by nsiti** [comment]
Thank you!
