### ISSUE TITLE
[Enhancement] Allow users to save their preferred/default manual search options

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#739]
At the moment, whenever I want to start a new manual search, I can only choose the category and tracker, but I cannot choose the number of entries per page, nor can I choose how to order the search results until after the results are displayed,. Having to do that after every search is a little cumbersome and repetitive. 

I suggest allowing the user to save his/her preferred or default search options so they can just search & display the results using these options every time by default. These options can include:

1. Setting the number of entries per page by default
2. Adding a tickbox option to allow the user to include or exclude dead torrents (with the ability to set this by default)
3. Allowing the user to choose how to order the search results (i.e. by size, by seeds, by grabs, etc)

Other options can be added in due course, but I believe these are the most relevant ones. Thanks a lot!

**Comment by armani316** [comment]
Are there plans to implement this in the future?

**Comment by kaso17** [comment]
definitely, but I've no schedule for it yet.

**Comment by kaso17** [comment]
5863bf18089b0f791499d4a3b56d0c6ee8ca8cf9 should take care of point 1 and 3 (number of entries and order/filter preferences should be store in the local storage now).

**Comment by armani316** [comment]
@kaso17 Works great for me! Thank you!

**Comment by armani316** [comment]
Update: This doesn't seem to work all the time. I find myself having to reset the number & order of entries every now and then.

**Comment by kaso17** [comment]
2086811596bdb071f68500202e8df85e710543ba should fix it

**Comment by armani316** [comment]
@kaso17 Seems like the default settings still get reset when I shut down and restart Jackett. Is there a way to permanently store them? Would it be a good idea to add a GUI for points 1-3 on the Manual search window? 

Running Jackett 0.7.969.0 on Windows 10

**Comment by kaso17** [comment]
With the update to 0.7.969 the previous settings are lost.
Restarting jackett shouldn't have an impact at all as the state is stored on the client side (in the localStorage of your browser).
If you're using some privacy extensions or similar which regularly deletes the localStorage try to disable them for jackett.

**Comment by kaso17** [comment]
What do you mean with "add a GUI for points 1-3 on the Manual search window"? For 1+3 the options should be already there, 2 isn't implemented yet.

**Comment by armani316** [comment]
@kaso17 I'll double check my Ad- and Pop-up block extensions. 

As for the GUI, what I had in mind originally is that when a user clicks the green Manual Search button, it would be great if he/she can see their current default search options before actually conducting a search, so they'd see (and can change ) how many entries per page they'd get, how the results would be ordered, and whether or not dead torrents would be displayed, before a search is conducted.

What do you think?

**Comment by kaso17** [comment]
we could render the empty table before the search, that wouldn't be much of a problem.
Or do you mean that these options should be sent to the corresponding trackers too? That would be a much bigger change.

**Comment by armani316** [comment]
@kaso17 Yes, I think rendering the empty table before the search would be a good idea, That way, even if, for whatever reason, the default search options have been reset/deleted, the user can quickly set them again before searching. 

Also, somewhere next to the 'Show [drop-down list] entries', a tickbox for show/hide dead torrents should be available once that's eventually implemented.

**Comment by kaso17** [comment]
132fa71e3541cf86e2747922e0ddabd9497183d7 now always shows the table (I'm not yet sure if I like it) and will clear the filter on every search.

**Comment by armani316** [comment]
@kaso17 I agree that despite its practicality, it's not necessarily the most elegant solution.  

A better implementation would be a drop-down list of all the table headers (i.e. size, seeds, grabs, name, etc.). This way the user can see (and choose) how results will be ordered without having to render an empty table (which I now realize can be confusing since it kinda shows that there are no search results even while you're still in the process of searching). 

This drop-down list can go between 'Show [drop-down list] entries' and the 'Show/Hide Dead Torrents' tickbox. What do you think?

**Comment by kaso17** [comment]
dead torrent filter was added with c17294052d58d78e4ebb4ce56982d759743fa38b

**Comment by kaso17** [comment]
1a79bf3219507cec6c500a8125b8befa3cf749e2 will show only the headers on the initial search open. Still not sure if I like it.

**Comment by armani316** [comment]
Thank you. I'm using using 0.7.993 - A couple of points:

1. Thank you for adding the 'Show dead torrents' tickbox. Is it possible to have this tickbox appear even after the results are displayed? Even if the user can tick/untick this box before searching, I think it would be convenient to have this option appear even after the results are displayed, so the user can toggle between showing and hiding dead torrents if they wish to. 

2. Thank you for hiding the empty table, however, I cannot see the table headers with the new update. Are you able to see and sort by them? Either way, I agree that this is still not be the neatest implementation. What do you think of the drop-down list idea that I proposed earlier? All table headers are available in a a drop-down list, the user can choose to sort by, e.g. size, by picking it from the list, and then choose whether to display the results ascendingly or descendingly (up/down arrows next to the drop-down list). This way we can avoid displaying an empty table or even a row of table headers, As with point no. 1 above, this box should continue to appear after the results are displayed. 

Thoughts?

**Comment by armani316** [comment]
@kaso17 Adding to point no. 2 from my previous post, I just realized that having both a drop-down list and sortable table headers - which will inevitably appear after search results are displayed - would be redundant. So maybe display the drop-down list before a search is conducted, and then have it disappear when search results are displayed? If users want to re-sort the results after they're displayed, they can use the table headers to do that.

**Comment by kaso17** [comment]
1) It should be shown always, seem like there's a bug. Which browser version are you using?

2) Could show the column headers too, then it would look like this: http://i.share.pho.to/ff3c6c1a_o.png
I don't like the idea of having a drop down for sort order before the search as it would somehow imply that the selection impacts the search results, it's adding to the overall usage complexity (two different things doing the same thing), additional code to maintain. And overall the concept of order first - search later seems unnatural to me (searching first and then sorting/filtering the results feels more natural).

**Comment by armani316** [comment]
1. I should have updated my statement. The 'Show dead torrents' now always appears, before & after the search results are displayed. I think I had a bug initially, but it's no longer there, so this isn't an issue anymore. I'm using the latest version of Firefox x64 on Windows 10.

2. Alright, I agree with you regrading the drop-down list. Let's not go with that option. I think the screenshot you just uploaded looks ideal for now. To me the idea behind displaying the search/sort options **_before_** searching is to allow the user to save their default/preferred search results so they wouldn't have to repeat them after every search, It also helps the user to make sure those options are actually saved. I'm still having an issue where I have to set these options every time I shut down Jackett (i.e. by closing the Jackett's background processes), which I do regularly when Jackett's performance starts slowing down.

3. Another small point that just occurred to me: After the search results are displayed, if the user conducts another search in the same window, the results from the 1st search remain displayed until the results from the 2nd search are shown. Do you think it's a good idea to clear the table between the two searches?

**Comment by kaso17** [comment]
2) ok, will do the changes.
Changes should be stored everytime you make a change on the client side.
If you use the web developers tools (F12) any go to the Console tab and put in the following command you should see the current settings:
`localStorage["DataTables_jackett-search-results-datatable_/Admin/Dashboard"]`

**Comment by armani316** [comment]
@kaso17 Got it, but it seems like every time I shut down Jackett's background processes, the settings are reset back to their original values (not the ones I last saved). Is this normal, or is it caused by something I'm doing?

**Comment by kaso17** [comment]
d9008e5e8cc8fce8d1f1636f3b979ed37f35fdec takes care of 2/3.
Restarting jacket should have absolutely no impact on the settings.
As long as you're accessing jackett via the same browser profile using the same URL the settings should be saved.

**Comment by armani316** [comment]
2 & 3 are working fine now, thanks! Yes, I am accessing Jackett using the same browser & URL, I'll keep testing this a little more to see if it works fine.

One last thing. Can the search filter be automatically cleared? I mean between searches on the same window, when existing a current manual search & starting a new one (in the same Jackett tab/window), and also when conducting another search concurrently on a separate tab. I don't think the search filter keywords should ever be stored/retained after a search is done.

**Comment by kaso17** [comment]
filter clearing should be fixed for manual search with d8d437bf1ab62f7c92404b856d8d5b97ee3c08b8 and for the unconfigured indexers with 510385f709bd382b490da3459ef17f89e006a43a
Will keep it active for normal configured indexers list for now (has been very useful during development).

**Comment by armani316** [comment]
@kaso17 Small usability enhancement: The keywords entered in the 'Search' filter are cleared between searches, but the keywords disappear only after the search has concluded (i.e. right when the search results for the 2nd search are returned).

Is it possible to clear the keywords right after clicking the Search button for the 2nd search? I think it makes more sense that the user does not see the old filter keywords while a new search is being conducted.

**Comment by kaso17** [comment]
fixed with ff70548bf528feba5151a9136e3123963a652f04

**Comment by 07416** [comment]
I can't understand if the search preferences are supposed to be saved. The number of results always resets to 20 after closing the Jackett tab.
