### ISSUE TITLE
The couch Potato can't search only torrent name, if i use Jackett (Ncore tracker)

### ISSUE THREAD

**Issue by vampywiz17** [Jackett/Jackett#796]
If i try to search a movie that the torrent name is "Bad Santa" and the IMDB name is "Tapló télapó" (Hungarian name) the Couch Potato found it, but if it is reverse (the torrent name the hungarian name, and the IMDB name is the english one) the Couch Potato can't find the Movie. The jackett manual search working well, the problem exist only in Couch Potato.

**Comment by kaso17** [comment]
most likely an encoding issue.
Can you send an invite to kaso1717 -at- gmail.com, so I can debug and fix it?

**Comment by vampywiz17** [comment]
unfortunatelly i cant invite... No other method to fix this?

**Comment by kaso17** [comment]
with an invite it would be much faster to debug it.

**Comment by vampywiz17** [comment]
I know, but i can't send it, because it need a higher rank in this site, that able to send a invite.

**Comment by armani316** [comment]
@kaso17 Is an nCore invite still required?

**Comment by kaso17** [comment]
yes, an invite is still required

**Comment by armani316** [comment]
@kaso17 Invite sent. Please confirm.

**Comment by kaso17** [comment]
invite received, thank you

**Comment by kaso17** [comment]
0f7ff3fb06b1a58322dfb5b4ef4d5b2c40788763 should fix it

**Comment by vampywiz17** [comment]
This problem is not fixed... :(

![01](https://cloud.githubusercontent.com/assets/14281430/22902009/e59f2ee8-f233-11e6-83bf-08df2015e67a.png)
![02](https://cloud.githubusercontent.com/assets/14281430/22902008/e59c16ae-f233-11e6-8112-3eca4f46b6f7.png)

**Comment by kaso17** [comment]
Are you sure couchpotato was searching with the hungarian name?
With the Hungarien name I didn't get any results due to the special characters in the movie name.
http://127.0.0.1:9117/potato/ncore/api?imdbid=tt2494376&search=A%20S%C3%B6t%C3%A9t%20Igazs%C3%A1g%20Lig%C3%A1ja&user=&passkey=<removed>

I disabled title filtering for results with imdb id (fa918481269ad8a401b38dc702fd970bc81c8d75). Now I'm getting all results

**Comment by kaso17** [comment]
Also added 3f8c87ad7f373db5a8032817c18529f09109d039 to make the title comparison ignore culture specific characters (e.g. á now equals a).

I assume you want couchpotato to download the hun releases, (not the english ones). can you filter the releases in couchpotato accordingly? Otherwise we probably have to revert fa918481269ad8a401b38dc702fd970bc81c8d75

**Comment by vampywiz17** [comment]
Great! How to test it? It will come a future release?

I don't filter it, not use automatic download. I search the releases manually.

**Comment by kaso17** [comment]
It's included in v0.7.1025

**Comment by vampywiz17** [comment]
I tried it, but same result. only two release. it not found the hungarian name/english IMDB title releases.

**Comment by kaso17** [comment]
Please check the logs and post the lines containing the Jackett HTTP request.

**Comment by vampywiz17** [comment]
Couchpoato log:

`02-15 22:27:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt2494376/, data: [][0m
02-15 22:27:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2494376, data: [][0m
02-15 22:27:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt2494376/?ignore=1, data: [][0m
02-15 22:27:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt2494376?api_key=xxx&append_to_response=alternative_titles&language=en, data: [][0m
02-15 22:27:31 INFO [0m[ie.providers.info.omdbapi] Found: Justice League Dark (2017)[0m
02-15 22:27:31 INFO [0m[ie.providers.info.omdbapi] Found: Justice League Dark (2017)[0m
02-15 22:27:32 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt2494376/, data: [][0m
02-15 22:27:32 INFO [0m[core.media.movie.searcher] Search for Justice League Dark in 720p ignoring ETA[0m
02-15 22:27:32 INFO [0m[hpotato.core.plugins.base] Opening url: get http://192.168.31.105:9117/potato/ncore?imdbid=tt2494376&search=Justice+League+Dark+2017&user=&passkey=xxx[0m
02-15 22:27:32 INFO [0m[core.media.movie.searcher] Search for Justice League Dark in 1080p ignoring ETA[0m
02-15 22:27:32 INFO [0m[edia._base.providers.base] Found: score(674) on TorrentPotato, 192.168.31.105: Justice.League.Dark.2017.1080p.Blu-ray.Remux.AVC.DTS-HD.MA.5.1.HUN-GS88[nCore][0m
02-15 22:27:32 INFO [0m[edia._base.providers.base] Found: score(674) on TorrentPotato, 192.168.31.105: Justice.League.Dark.2017.1080p.Blu-ray.Remux.AVC.DTS-HD.MA.5.1.HUN-GS88[nCore][0m
02-15 22:27:32 INFO [0m[tato.core.plugins.release] Tried to download, but none of the "torrent" downloaders are enabled or gave an error[0m
02-15 22:27:32 INFO [0m[core.media.movie.searcher] Search for Justice League Dark in BR-Rip ignoring ETA[0m
02-15 22:27:32 INFO [0m[edia._base.providers.base] Found: score(3058) on TorrentPotato, 192.168.31.105: Justice.League.Dark.2017.1080p.WEB-DL.DD5.1.H264-FGT[nCore][0m
02-15 22:27:32 INFO [0m[edia._base.providers.base] Found: score(3058) on TorrentPotato, 192.168.31.105: Justice.League.Dark.2017.1080p.WEB-DL.DD5.1.H264-FGT[nCore][0m
02-15 22:27:32 INFO [0m[tato.core.plugins.release] Tried to download, but none of the "torrent" downloaders are enabled or gave an error[0m
02-15 22:27:32 INFO [0m[core.media.movie.searcher] Search for Justice League Dark in DVD-Rip ignoring ETA[0m
`

**Comment by vampywiz17** [comment]
I found a interesting thing. 

If i search on jackett manual with **"Year"**

Same with Couchpotato (+DVD9 but it not important, it is not part of "Best" quality group)

![image](https://cloud.githubusercontent.com/assets/14281430/22997740/f7fc0290-f3d3-11e6-94d0-813cad13eee6.png)

If i search on jackett manual without **"Year"**

It found all of them.

![image](https://cloud.githubusercontent.com/assets/14281430/22997810/3aa93536-f3d4-11e6-83f9-56a0dc2b79ad.png)

**Comment by kaso17** [comment]
If you check the log you'll see that couchpotato searches for "Justice League Dark 2017".
The year makes the difference, if you search with/without the year directly on the tracker you'll get the same results.

I suggest you open a bugreport/suggestion in their forum.

The best option would be if they would support searching by the imdbid e.g. searching for "tt2494376" would return all corresponding torrents, independent of the language.

**Comment by kaso17** [comment]
In the mean time I believe couchpotato has an option to search without the year which might be a workaround for the problem.

**Comment by kaso17** [comment]
Regarding the missing DVD9 release: I can't reproduce it.
What happens if you open http://192.168.31.105:9117/potato/ncore?imdbid=tt2494376&search=Justice+League+Dark+2017&user=&passkey=xxx in your browser? It should return all 3 releases.

**Comment by vampywiz17** [comment]
The reason, that i cant find the DVD9 release, that it is not part of "Best" quality. 

It is not a error, it is normal.

![image](https://cloud.githubusercontent.com/assets/14281430/23042794/58ced3f6-f49a-11e6-9874-466615266d78.png)


I try to open a bug report on CP. I cant found any option how ti disable year...

**Comment by vampywiz17** [comment]
I tried it with Radarr (Sonarr fork, use with movies) same problem, it search with year... It possible that it is Jackett error maybe...

![image](https://cloud.githubusercontent.com/assets/14281430/23045678/fab9b5c2-f4a5-11e6-859c-6e2f94f454c6.png)

**Comment by kaso17** [comment]
Definitely not a jackett issue. Did you open a bugreport/suggestion in the ncore forum?
If they say that they won't fix it I'll implement a workaround (stripping the year in jackett).

**Comment by vampywiz17** [comment]
Ohh i think that need to report it in Coachpotato forum. Sorry i will report it on Ncore.

**Comment by vampywiz17** [comment]
Good news! 

The Ncore staff answer to me, that they already working on search with IMDB ID!

**Comment by kaso17** [comment]
ok, please let us know once they support it.
