### ISSUE TITLE
TorrentBD: "Login failed: No form found "

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#910]
Running Jackett as a service on Windows10E

	
Error on 20170103102443 for TorrentBD.txtJackett.ExceptionWithConfigData: Login failed: No form found on http://www.torrentbd.com/torrent/account-login.php using form selector form[action="account-login.php"]
   at Jackett.Indexers.CardigannIndexer.<DoLogin>d__32.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 437
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__41.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 885

**Comment by kaso17** [comment]
I assume it's happening during a search?
Then most likely the cloudflare clearance is expired and you've to reconfigure it (solve the captcha).
In my case I've to solve the catpcha every few hours making the indexer pretty much useless. For other's it apparently lasting longer.

**Comment by seanvree** [comment]
@kaso17  - It's not when I search, It's when I'm trying to log in. 

Can you get to a log in page now?  If so, what's the URL?

**Comment by kaso17** [comment]
I've tested it earlier and now again, I can configure/login fine using the latest jackett version on Windows 7.
Remote login via cookie requires some extra work (are you trying that?)
Are you seeing the captcha in the configuration dialog?

Please enable enhanced logging and post the log output.

**Comment by seanvree** [comment]
Yeah, I've tried from my seedbox that's behind a Canadian VPN, as well as numerous browsers.  

What login URL are you using?

Here's the debug log:

https://drive.google.com/file/d/0B7OujkYtbxFNdDBJSUhkMTBIeXc/view?usp=sharing

**Comment by ShahadatRD** [comment]
most provably your seedbox ip address is having a block from cludflare and that's having issue in captcha

**Comment by seanvree** [comment]
Hey @kaso17 @ShahadatRD  - Thanks for your guys' help. This is really bothering me!

So I downgraded my Chome to the standalone Chromium 47, but I'm still having the same issue! Here is my dev console when trying to access TorrentBD:

=================================================
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://www.torrentbd.com/torrent/:1 GET https://www.torrentbd.com/torrent/ 500 (OK)
Navigated to https://www.torrentbd.com/torrent/
favicon.ico:1 GET https://www.torrentbd.com/favicon.ico 404 (OK)
Navigated to https://www.torrentbd.com/
(index):1 Mixed Content: The page at 'https://www.torrentbd.com/' was loaded over HTTPS, but requested an insecure image 'http://i1083.photobucket.com/albums/j385/skbms11/bg1.jpg'. This content should also be served over HTTPS.
/torrent/index.php:1 GET https://www.torrentbd.com/torrent/index.php 500 (OK)
Navigated to https://www.torrentbd.com/torrent/index.php


Any ideas?

**Comment by ShahadatRD** [comment]
you better do a check by connecting to TorrentBD by using multi thread, and let me know what happens ! @seanvree

**Comment by seanvree** [comment]
@ShahadatRD - Multi Thread?  I'm not familiar.

**Comment by armani316** [comment]
@seanvree Is this still an issue?

**Comment by seanvree** [comment]
@armani316 - I was able to add the tracker, but it won't pass the test:

Error on 20170123162826 for TorrentBD.txtJackett.ExceptionWithConfigData: Login failed: No form found on http://www.torrentbd.com/torrent/account-login.php using form selector form[action="account-login.php"]
   at Jackett.Indexers.CardigannIndexer.<DoLogin>d__32.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 439
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__41.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 955

**Comment by kaso17** [comment]
Most likely you've to re-configure/add it again (I have to do it every 4 hours) due to an outdated cloud flare challenge

**Comment by seanvree** [comment]
Yeah, I can't figure it out @kaso17 I can get the main page:
https://www.torrentbd.com/

But when I try to get to https://www.torrentbd.com/torrent/index.php

I get error 500, I've tried by IP, and different browsers. I have no idea what I'm doing wrong.

**Comment by kaso17** [comment]
https://www.torrentbd.com/ is not cloud flare protected
https://www.torrentbd.com/torrent/index.php is
To solve the cloudflare challenge (500 error) you need to solve the captcha.
In my case I've to do it every 4 hours which makes this tracker supper annoying to use.
The best chance is to convince their staff to replace the captcha with the standard cloudflare javascript challenge.

**Comment by armani316** [comment]
@ShahadatRD If I'm not mistaken, you're either staff, or you work closely with them. Can you guys fix this issue?

**Comment by ShahadatRD** [comment]
i will look on this issue as soon as possible @armani316

**Comment by armani316** [comment]
@ShahadatRD Thank you! Keep us updated, please!

**Comment by ShahadatRD** [comment]
started a conversation with the SysOP of TBD. will let you know a update within next 48 hour. @kaso17 @seanvree @armani316

**Comment by armani316** [comment]
@ShahadatRD Any updates on this issue from the Sysop?

**Comment by ShahadatRD** [comment]
SysOP is working on updating the whole website. you know its bit hard for one guy to do that... after updating the whole website, he will look into the Cloudflare issue @armani316

**Comment by raspdealer** [comment]
Just as aditionnal information, I fixed an error like that just by updating my Mono version to the last one instead of 3.10.0 (most popular in online guides)

**Comment by armani316** [comment]
@kaso17 I'm guessing updating Mono did not solve this issue for you like it for @raspdealer?

**Comment by kaso17** [comment]
no, this is only fixable by changing the cloudflare settings for the page (Which only their admin can do).

**Comment by RoloSoze** [comment]
@kaso17 Since this is a tracker-caused issue, should it be closed?

**Comment by kaso17** [comment]
yes, closing for now
